#!/usr/bin/env bash

${CMAKE_COMMAND} \
  -DCMAKE_GENERATOR="${CMAKE_GENERATOR}" \
  -DCMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" \
  -DBUILD_TESTING=OFF \
  -DCATCH_INSTALL_DOCS=OFF \
  -B"${BINARY_DIR}" \
  -S"${SOURCE_DIR}"

${CMAKE_COMMAND} --build "${BINARY_DIR}" --parallel "${NEML2_CONTRIB_PARALLEL}"
${CMAKE_COMMAND} --install "${BINARY_DIR}"
