var searchData=
[
  ['identification_0',['Automatic input/output identification',['../system-models.html#automatic-input-output-identification',1,'']]],
  ['identitytensor_1',['IdentityTensor',['../syntax-tensors.html#identitytensor',1,'']]],
  ['implementation_2',['Implementation',['../tutorials-extension-the-forward-operator.html#autotoc_md110',1,'']]],
  ['implementation_20details_3',['Implementation details',['../reactive-infiltration.html#autotoc_md46',1,'Implementation details'],['../thermosetting-pyrolysis.html#autotoc_md65',1,'Implementation details']]],
  ['implicit_20function_20theorem_4',['Remarks on the implicit function theorem',['../tutorials-models-implicit-model.html#autotoc_md124',1,'']]],
  ['implicit_20model_5',['Implicit model',['../tutorials-models-implicit-model.html',1,'']]],
  ['implicitupdate_6',['ImplicitUpdate',['../syntax-models.html#implicitupdate',1,'ImplicitUpdate'],['../migration-211-212.html#predictor-migration',1,'Predictor moved from &lt;span class=&quot;tt&quot;&gt;TransientDriver&lt;/span&gt; into &lt;span class=&quot;tt&quot;&gt;ImplicitUpdate&lt;/span&gt;']]],
  ['importing_20required_20libraries_20and_20setting_20up_7',['Importing required libraries and setting up',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md168',1,'Importing required libraries and setting up'],['../python-examples-crystal_plasticity-polefigures.html#autotoc_md178',1,'Importing required libraries and setting up']]],
  ['in_20drivers_8',['Optional scheduler hookup in drivers',['../migration-200-210.html#autotoc_md21',1,'']]],
  ['in_20natural_20language_9',['Use LLM to explain NEML2 input file in natural language',['../python-examples-explain.html',1,'']]],
  ['in_20one_20sentence_10',['In one sentence',['../python-examples-explain.html#autotoc_md221',1,'']]],
  ['in_20the_20synthetic_20data_20and_20for_20our_20initial_20guess_20at_20the_20parameters_11',['in the synthetic data and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['in_20time_20compilation_12',['Just-in-time compilation',['../tutorials-models-just-in-time-compilation.html',1,'']]],
  ['independent_20and_20rate_20dependent_20flow_20rules_13',['6. Rate-independent and rate-dependent flow rules',['../python-examples-explain.html#autotoc_md212',1,'']]],
  ['indexing_14',['Indexing',['../tutorials-tensors-indexing.html',1,'']]],
  ['indexing_15',['indexing',['../tutorials-tensors-indexing.html#autotoc_md243',1,'Batch versus base indexing'],['../tutorials-tensors-indexing.html#autotoc_md244',1,'Single element indexing'],['../system-tensors.html#tensor-indexing',1,'Tensor indexing']]],
  ['indexing_20tools_16',['Dimensional indexing tools',['../tutorials-tensors-indexing.html#autotoc_md246',1,'']]],
  ['inferred_20posteriors_17',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md240',1,'']]],
  ['infiltration_18',['Reactive Infiltration',['../reactive-infiltration.html',1,'']]],
  ['initial_20guess_20at_20the_20parameters_19',['initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['initial_20parameter_20values_20',['Run the model with the initial parameter values',['../python-examples-deterministic.html#autotoc_md196',1,'']]],
  ['input_20file_21',['Example Input File',['../thermosetting-pyrolysis.html#autotoc_md66',1,'']]],
  ['input_20file_22',['Input file',['../tutorials-models-input-file.html',1,'Input file'],['../tutorials-extension-connection-to-input-files.html#autotoc_md100',1,'Input file'],['../tutorials-extension-model-composition.html#autotoc_md107',1,'Input file']]],
  ['input_20file_23',['input file',['../reactive-infiltration.html#autotoc_md47',1,'Complete input file'],['../tutorials-models-running-your-first-model.html#autotoc_md148',1,'Loading a model from the input file'],['../tutorials-models-model-composition.html#autotoc_md132',1,'Writing the input file'],['../tutorials-models-running-your-first-model.html#autotoc_md146',1,'Writing the input file']]],
  ['input_20file_20changes_24',['Input file changes',['../migration-200-210.html#autotoc_md19',1,'Input file changes'],['../migration-211-212.html#autotoc_md29',1,'Input file changes']]],
  ['input_20file_20in_20natural_20language_25',['Use LLM to explain NEML2 input file in natural language',['../python-examples-explain.html',1,'']]],
  ['input_20file_20syntax_26',['input file syntax',['../syntax-data.html#autotoc_md67',1,'Available objects and their input file syntax'],['../syntax-drivers.html#autotoc_md68',1,'Available objects and their input file syntax'],['../syntax-equationsystems.html#autotoc_md69',1,'Available objects and their input file syntax'],['../syntax-models.html#autotoc_md70',1,'Available objects and their input file syntax'],['../syntax-schedulers.html#autotoc_md71',1,'Available objects and their input file syntax'],['../syntax-settings.html#autotoc_md72',1,'Available objects and their input file syntax'],['../syntax-solvers.html#autotoc_md73',1,'Available objects and their input file syntax'],['../syntax-tensors.html#autotoc_md74',1,'Available objects and their input file syntax']]],
  ['input_20files_27',['Connection to input files',['../tutorials-extension-connection-to-input-files.html',1,'']]],
  ['input_20output_20identification_28',['Automatic input/output identification',['../system-models.html#automatic-input-output-identification',1,'']]],
  ['input_20tendors_29',['Create the input tendors',['../python-examples-statistical.html#autotoc_md228',1,'']]],
  ['input_20tensors_30',['Create the input tensors',['../python-examples-deterministic.html#autotoc_md190',1,'']]],
  ['inspection_31',['Model inspection',['../tutorials-extension-argument-declaration.html#autotoc_md98',1,'']]],
  ['installation_32',['Basic Installation',['../install.html',1,'']]],
  ['installation_33',['Quick installation',['../index.html#autotoc_md2',1,'']]],
  ['installation_20and_20integration_20changes_34',['Installation and integration changes',['../migration-200-210.html#autotoc_md24',1,'']]],
  ['installation_20layout_20components_35',['Installation layout/components',['../migration-200-210.html#autotoc_md26',1,'']]],
  ['integrated_20model_36',['pyzag driver for the integrated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md172',1,'']]],
  ['integration_37',['External Project Integration',['../external-project-integration.html',1,'']]],
  ['integration_38',['integration',['../external-project-integration.html#autotoc_md15',1,'CMake integration'],['../external-project-integration.html#autotoc_md14',1,'Makefile integration']]],
  ['integration_20changes_39',['Installation and integration changes',['../migration-200-210.html#autotoc_md24',1,'']]],
  ['integration_20options_40',['Integration options',['../migration-200-210.html#autotoc_md27',1,'']]],
  ['interact_41',['Key components and how they interact',['../python-examples-explain.html#autotoc_md206',1,'']]],
  ['interface_42',['Linear system interface',['../system-equationsystems.html#autotoc_md78',1,'']]],
  ['interpolation_43',['Cell-edge interpolation',['../finite-volume.html#autotoc_md34',1,'']]],
  ['into_20implicitupdate_44',['Predictor moved from &lt;span class=&quot;tt&quot;&gt;TransientDriver&lt;/span&gt; into &lt;span class=&quot;tt&quot;&gt;ImplicitUpdate&lt;/span&gt;',['../migration-211-212.html#predictor-migration',1,'']]],
  ['inverse_20pole_20figure_45',['Plot a discrete inverse pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md182',1,'']]],
  ['is_20now_20required_46',['&lt;span class=&quot;tt&quot;&gt;NonlinearSystem&lt;/span&gt;: &lt;span class=&quot;tt&quot;&gt;unknowns&lt;/span&gt; is now required',['../migration-211-212.html#nonlinearsystem-unknowns',1,'']]],
  ['is_20vectorization_47',['What is vectorization?',['../tutorials-models-vectorization.html#autotoc_md153',1,'']]],
  ['isotropic_20hardening_48',['Isotropic hardening',['../python-examples-explain.html#autotoc_md209',1,'3. Isotropic hardening'],['../solid-mechanics.html#autotoc_md55',1,'Isotropic hardening']]],
  ['isotropicelasticitytensor_49',['IsotropicElasticityTensor',['../syntax-models.html#isotropicelasticitytensor',1,'']]],
  ['isotropicmandelstress_50',['IsotropicMandelStress',['../syntax-models.html#isotropicmandelstress',1,'']]]
];
