var searchData=
[
  ['n_20suffix_0',['History variables renamed (&lt;span class=&quot;tt&quot;&gt;~N&lt;/span&gt; suffix)',['../migration-211-212.html#history-naming',1,'']]],
  ['name_1',['Tensor name',['../tutorials-models-model-parameters-revisited.html#autotoc_md142',1,'']]],
  ['naming_20conventions_2',['Naming Conventions',['../tutorials-naming-conventions.html',1,'']]],
  ['naming_20conventions_3',['Naming conventions',['../tutorials-naming-conventions.html#autotoc_md158',1,'']]],
  ['naming_20conventions_4',['naming conventions',['../tutorials-naming-conventions.html#autotoc_md160',1,'Source code naming conventions'],['../tutorials-naming-conventions.html#autotoc_md159',1,'Variable naming conventions']]],
  ['naming_3a_20subspace_20prefixes_20removed_5',['Variable naming: subspace prefixes removed',['../migration-211-212.html#variable-naming',1,'']]],
  ['natural_20language_6',['Use LLM to explain NEML2 input file in natural language',['../python-examples-explain.html',1,'']]],
  ['neml2_7',['NEML2',['../index.html#autotoc_md4',1,'Citing NEML2'],['../index.html',1,'NEML2']]],
  ['neml2_20input_20file_20in_20natural_20language_8',['Use LLM to explain NEML2 input file in natural language',['../python-examples-explain.html',1,'']]],
  ['neml2_20s_20broadcasting_20rules_9',['NEML2&apos;s broadcasting rules',['../tutorials-tensors-broadcasting.html#autotoc_md241',1,'']]],
  ['new_20engineering_20material_20model_20library_20version_202_10',['The New Engineering Material model Library, version 2',['../index.html#autotoc_md1',1,'']]],
  ['new_20top_20level_20sections_11',['New top-level sections',['../migration-200-210.html#autotoc_md20',1,'']]],
  ['newton_12',['Newton',['../syntax-solvers.html#newton',1,'']]],
  ['newtonwithlinesearch_13',['NewtonWithLineSearch',['../syntax-solvers.html#newtonwithlinesearch',1,'']]],
  ['next_20steps_14',['Next steps',['../tutorials-next-steps.html',1,'']]],
  ['nonlinear_20functions_15',['Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions',['../tutorials-optimization-pyzag.html#autotoc_md165',1,'']]],
  ['nonlinear_20solver_16',['Nonlinear solver',['../system-solvers.html#autotoc_md88',1,'']]],
  ['nonlinear_20solvers_20now_20reference_20a_20linear_20solver_17',['Nonlinear solvers now reference a linear solver',['../migration-200-210.html#linear_solver',1,'']]],
  ['nonlinear_20system_18',['Nonlinear system',['../system-equationsystems.html#autotoc_md79',1,'Nonlinear system'],['../system-solvers.html#autotoc_md89',1,'Nonlinear system']]],
  ['nonlinear_20system_19',['Model-based nonlinear system',['../system-equationsystems.html#autotoc_md80',1,'']]],
  ['nonlinearsystem_20',['NonlinearSystem',['../migration-200-210.html#eqsys',1,'Migration to EquationSystems (&lt;span class=&quot;tt&quot;&gt;NonlinearSystem&lt;/span&gt;)'],['../syntax-equationsystems.html#nonlinearsystem',1,'NonlinearSystem']]],
  ['nonlinearsystem_3a_20unknowns_20is_20now_20required_21',['&lt;span class=&quot;tt&quot;&gt;NonlinearSystem&lt;/span&gt;: &lt;span class=&quot;tt&quot;&gt;unknowns&lt;/span&gt; is now required',['../migration-211-212.html#nonlinearsystem-unknowns',1,'']]],
  ['normality_22',['Normality',['../syntax-models.html#normality',1,'']]],
  ['notable_20parameters_23',['Physical meaning of notable parameters',['../python-examples-explain.html#autotoc_md216',1,'']]],
  ['notebooks_24',['Jupyter Notebooks',['../tutorials-notebooks.html',1,'']]],
  ['notebooks_25',['Jupyter notebooks',['../tutorials-contributing.html#autotoc_md93',1,'']]],
  ['now_20reference_20a_20linear_20solver_26',['Nonlinear solvers now reference a linear solver',['../migration-200-210.html#linear_solver',1,'']]],
  ['now_20required_27',['&lt;span class=&quot;tt&quot;&gt;NonlinearSystem&lt;/span&gt;: &lt;span class=&quot;tt&quot;&gt;unknowns&lt;/span&gt; is now required',['../migration-211-212.html#nonlinearsystem-unknowns',1,'']]],
  ['now_20sample_20at_20run_20at_20a_20fixed_20condition_28',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md232',1,'']]],
  ['numeric_20literal_29',['Plain numeric literal',['../tutorials-models-model-parameters-revisited.html#autotoc_md141',1,'']]],
  ['numerical_20experiment_30',['For loop versus vectorization: A numerical experiment',['../tutorials-models-vectorization.html#autotoc_md154',1,'']]]
];
