var searchData=
[
  ['package_0',['package',['../install.html#autotoc_md13',1,'Python package'],['../tutorials-contributing.html#autotoc_md92',1,'Python package']]],
  ['packaging_1',['Python packaging',['../migration-200-210.html#autotoc_md28',1,'']]],
  ['parameter_20calibration_2',['Parameter calibration',['../tutorials-optimization-parameter-calibration.html',1,'']]],
  ['parameter_20declaration_3',['Parameter declaration',['../tutorials-extension-argument-declaration.html#autotoc_md97',1,'']]],
  ['parameter_20derivatives_20of_20recursive_20nonlinear_20functions_4',['Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions',['../tutorials-optimization-pyzag.html#autotoc_md165',1,'']]],
  ['parameter_20specification_5',['Parameter specification',['../tutorials-models-model-parameters-revisited.html#autotoc_md140',1,'']]],
  ['parameter_20value_6',['parameter value',['../tutorials-models-model-parameters.html#autotoc_md137',1,'Retrieving the parameter value'],['../tutorials-models-model-parameters.html#autotoc_md138',1,'Updating the parameter value']]],
  ['parameter_20values_7',['parameter values',['../tutorials-getting-started.html#autotoc_md116',1,'Modifying parameter values'],['../python-examples-deterministic.html#autotoc_md196',1,'Run the model with the initial parameter values']]],
  ['parameter_20vs_20buffer_8',['Parameter vs buffer',['../tutorials-models-model-parameters.html#autotoc_md136',1,'']]],
  ['parameters_9',['parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../tutorials-models-model-parameters.html',1,'Model parameters'],['../python-examples-explain.html#autotoc_md216',1,'Physical meaning of notable parameters'],['../python-examples-deterministic.html#autotoc_md195',1,'Scale the model parameters'],['../python-examples-statistical.html#autotoc_md234',1,'Scale the model parameters']]],
  ['parameters_20related_20to_20how_20we_20calibrate_20the_20model_10',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model',['../python-examples-deterministic.html#autotoc_md185',1,'']]],
  ['parameters_20related_20to_20how_20we_20train_20the_20model_11',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model',['../python-examples-statistical.html#autotoc_md222',1,'']]],
  ['parameters_20revisited_12',['Model parameters (revisited)',['../tutorials-models-model-parameters-revisited.html',1,'']]],
  ['parameters_20with_20random_20values_13',['parameters with random values',['../python-examples-deterministic.html#autotoc_md191',1,'Replace the model parameters with random values'],['../python-examples-statistical.html#autotoc_md229',1,'Replace the model parameters with random values']]],
  ['parser_14',['Parser',['../tutorials-extension-connection-to-input-files.html#autotoc_md99',1,'']]],
  ['perfectly_20plastic_20yield_20function_15',['Perfectly Plastic Yield function',['../solid-mechanics.html#autotoc_md54',1,'']]],
  ['perslipforestdislocationevolution_16',['PerSlipForestDislocationEvolution',['../syntax-models.html#perslipforestdislocationevolution',1,'']]],
  ['perzynaplasticflowrate_17',['PerzynaPlasticFlowRate',['../syntax-models.html#perzynaplasticflowrate',1,'']]],
  ['phase_20field_20fracture_18',['Phase-Field Fracture',['../phase-field-fracture.html',1,'']]],
  ['phasetransformationeigenstrain_19',['PhaseTransformationEigenstrain',['../syntax-models.html#phasetransformationeigenstrain',1,'']]],
  ['philosophy_20',['Features and design philosophy',['../index.html#autotoc_md3',1,'']]],
  ['physical_20meaning_20of_20notable_20parameters_21',['Physical meaning of notable parameters',['../python-examples-explain.html#autotoc_md216',1,'']]],
  ['picture_22',['High-level picture',['../python-examples-explain.html#autotoc_md205',1,'']]],
  ['plain_20numeric_20literal_23',['Plain numeric literal',['../tutorials-models-model-parameters-revisited.html#autotoc_md141',1,'']]],
  ['plastic_20yield_20function_24',['Perfectly Plastic Yield function',['../solid-mechanics.html#autotoc_md54',1,'']]],
  ['plasticdeformationrate_25',['PlasticDeformationRate',['../syntax-models.html#plasticdeformationrate',1,'']]],
  ['plasticity_26',['plasticity',['../python-examples-explain.html#autotoc_md211',1,'5. Flow direction: associative plasticity'],['../solid-mechanics.html#autotoc_md51',1,'Consistent plasticity'],['../solid-mechanics.html#autotoc_md61',1,'Crystal plasticity']]],
  ['plasticity_20formulations_27',['Crystal plasticity formulations',['../python-examples-crystal_plasticity-compare_formulations.html',1,'']]],
  ['plasticity_20macroscale_28',['Plasticity (macroscale)',['../solid-mechanics.html#autotoc_md50',1,'']]],
  ['plasticspatialvelocitygradient_29',['PlasticSpatialVelocityGradient',['../syntax-models.html#plasticspatialvelocitygradient',1,'']]],
  ['plasticvorticity_30',['PlasticVorticity',['../syntax-models.html#plasticvorticity',1,'']]],
  ['plot_20a_20continuous_20polefigure_31',['Plot a continuous polefigure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md184',1,'']]],
  ['plot_20a_20discrete_20inverse_20pole_20figure_32',['Plot a discrete inverse pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md182',1,'']]],
  ['plot_20a_20discrete_20pole_20figure_33',['Plot a discrete pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md181',1,'']]],
  ['plot_20some_20comparisons_20of_20the_20elastic_20strains_34',['Plot some comparisons of the elastic strains',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md177',1,'']]],
  ['plot_20the_20calibrated_20model_20predictions_35',['Plot the calibrated model predictions',['../python-examples-deterministic.html#autotoc_md198',1,'']]],
  ['plot_20the_20pole_20figures_36',['Plot the pole figures',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md176',1,'']]],
  ['plot_20the_20synthetic_20data_37',['Plot the synthetic data',['../python-examples-deterministic.html#autotoc_md193',1,'Plot the synthetic data'],['../python-examples-statistical.html#autotoc_md231',1,'Plot the synthetic data']]],
  ['plotting_20polefigures_38',['Plotting polefigures',['../python-examples-crystal_plasticity-polefigures.html',1,'']]],
  ['pole_20figure_39',['pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md182',1,'Plot a discrete inverse pole figure'],['../python-examples-crystal_plasticity-polefigures.html#autotoc_md181',1,'Plot a discrete pole figure']]],
  ['pole_20figures_40',['Plot the pole figures',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md176',1,'']]],
  ['polefigure_41',['Plot a continuous polefigure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md184',1,'']]],
  ['polefigures_42',['Plotting polefigures',['../python-examples-crystal_plasticity-polefigures.html',1,'']]],
  ['posteriors_43',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md240',1,'']]],
  ['posteriors_20and_20inferred_20posteriors_44',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md240',1,'']]],
  ['powerdegradationfunction_45',['PowerDegradationFunction',['../syntax-models.html#powerdegradationfunction',1,'']]],
  ['powerlawisotropichardeningstaticrecovery_46',['PowerLawIsotropicHardeningStaticRecovery',['../syntax-models.html#powerlawisotropichardeningstaticrecovery',1,'']]],
  ['powerlawkinematichardeningstaticrecovery_47',['PowerLawKinematicHardeningStaticRecovery',['../syntax-models.html#powerlawkinematichardeningstaticrecovery',1,'']]],
  ['powerlawpermeability_48',['PowerLawPermeability',['../syntax-models.html#powerlawpermeability',1,'']]],
  ['powerlawsliprule_49',['PowerLawSlipRule',['../syntax-models.html#powerlawsliprule',1,'']]],
  ['predictions_50',['Plot the calibrated model predictions',['../python-examples-deterministic.html#autotoc_md198',1,'']]],
  ['predictor_20moved_20from_20transientdriver_20into_20implicitupdate_51',['Predictor moved from &lt;span class=&quot;tt&quot;&gt;TransientDriver&lt;/span&gt; into &lt;span class=&quot;tt&quot;&gt;ImplicitUpdate&lt;/span&gt;',['../migration-211-212.html#predictor-migration',1,'']]],
  ['prefixes_20removed_52',['Variable naming: subspace prefixes removed',['../migration-211-212.html#variable-naming',1,'']]],
  ['prerequisites_53',['Prerequisites',['../install.html#autotoc_md11',1,'']]],
  ['presets_54',['presets',['../build-customization.html#autotoc_md7',1,'Build presets'],['../build-customization.html#autotoc_md6',1,'Configure presets']]],
  ['print_20the_20calibrated_20model_20coefficients_55',['Print the calibrated model coefficients',['../python-examples-deterministic.html#autotoc_md199',1,'']]],
  ['prior_20model_20to_20compare_20to_20the_20repeated_20test_56',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md236',1,'']]],
  ['priors_20true_20posteriors_20and_20inferred_20posteriors_57',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md240',1,'']]],
  ['problem_20definition_58',['Problem definition',['../tutorials-extension-model-composition.html#autotoc_md106',1,'Problem definition'],['../tutorials-optimization-parameter-calibration.html#autotoc_md163',1,'Problem definition']]],
  ['problem_20description_59',['Problem description',['../tutorials-extension.html#autotoc_md103',1,'Problem description'],['../tutorials-models-implicit-model.html#autotoc_md121',1,'Problem description'],['../tutorials-models-just-in-time-compilation.html#autotoc_md126',1,'Problem description'],['../tutorials-models-model-composition.html#autotoc_md131',1,'Problem description'],['../tutorials-models-model-parameters.html#autotoc_md135',1,'Problem description'],['../tutorials-models-model-parameters-revisited.html#autotoc_md139',1,'Problem description'],['../tutorials-models-running-your-first-model.html#autotoc_md144',1,'Problem description'],['../tutorials-models-transient-driver.html#autotoc_md151',1,'Problem description']]],
  ['project_60',['Downstream C++ project',['../tutorials-getting-started.html#autotoc_md112',1,'']]],
  ['project_20integration_61',['External Project Integration',['../external-project-integration.html',1,'']]],
  ['projectiles_62',['Lauching the projectiles',['../tutorials-extension-model-composition.html#autotoc_md108',1,'']]],
  ['prompt_63',['Build the prompt',['../python-examples-explain.html#autotoc_md203',1,'']]],
  ['pyrolysis_64',['Thermosetting Pyrolysis',['../thermosetting-pyrolysis.html',1,'']]],
  ['pytest_65',['pytest',['../tutorials-contributing.html#testing-pytest',1,'']]],
  ['python_20package_66',['Python package',['../install.html#autotoc_md13',1,'Python package'],['../tutorials-contributing.html#autotoc_md92',1,'Python package']]],
  ['python_20packaging_67',['Python packaging',['../migration-200-210.html#autotoc_md28',1,'']]],
  ['python_20script_68',['Python script',['../tutorials-getting-started.html#autotoc_md113',1,'']]],
  ['python_20stubs_69',['Python stubs',['../tutorials-contributing.html#testing-python-stubs',1,'']]],
  ['pyzag_70',['pyzag',['../tutorials-optimization-pyzag.html',1,'']]],
  ['pyzag_20driver_71',['pyzag driver',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md179',1,'']]],
  ['pyzag_20driver_20for_20the_20integrated_20model_72',['pyzag driver for the integrated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md172',1,'']]],
  ['pyzag_20driver_20for_20the_20separated_20model_73',['pyzag driver for the separated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md169',1,'']]]
];
