var searchData=
[
  ['macroscale_0',['Plasticity (macroscale)',['../solid-mechanics.html#autotoc_md50',1,'']]],
  ['makefile_20integration_1',['Makefile integration',['../external-project-integration.html#autotoc_md14',1,'']]],
  ['management_2',['Dependency management',['../dependency-management.html',1,'']]],
  ['material_20model_20calibration_3',['Deterministic material model calibration',['../python-examples-deterministic.html',1,'']]],
  ['material_20model_20learning_4',['Statistical material model learning',['../python-examples-statistical.html',1,'']]],
  ['material_20model_20library_20version_202_5',['The New Engineering Material model Library, version 2',['../index.html#autotoc_md1',1,'']]],
  ['meaning_20of_20notable_20parameters_6',['Physical meaning of notable parameters',['../python-examples-explain.html#autotoc_md216',1,'']]],
  ['measure_20and_20equivalent_20stress_7',['1. Stress measure and equivalent stress',['../python-examples-explain.html#autotoc_md207',1,'']]],
  ['mechanics_8',['Solid Mechanics',['../solid-mechanics.html',1,'']]],
  ['mechanisms_9',['Reaction mechanisms',['../chemical-reactions.html#autotoc_md30',1,'']]],
  ['method_20signature_10',['Method signature',['../tutorials-extension-the-forward-operator.html#autotoc_md109',1,'']]],
  ['methods_11',['Factory methods',['../tutorials-tensors-tensor-creation.html#autotoc_md248',1,'']]],
  ['migrating_20from_20v2_200_200_20to_20v2_201_200_12',['Migrating from v2.0.0 to v2.1.0',['../migration-200-210.html',1,'']]],
  ['migrating_20from_20v2_201_201_20to_20v2_201_202_13',['Migrating from v2.1.1 to v2.1.2',['../migration-211-212.html',1,'']]],
  ['migration_20to_20equationsystems_20nonlinearsystem_14',['Migration to EquationSystems (&lt;span class=&quot;tt&quot;&gt;NonlinearSystem&lt;/span&gt;)',['../migration-200-210.html#eqsys',1,'']]],
  ['millerindex_15',['MillerIndex',['../syntax-tensors.html#millerindex',1,'']]],
  ['millerindexconstantparameter_16',['MillerIndexConstantParameter',['../syntax-models.html#millerindexconstantparameter',1,'']]],
  ['millerindexdynamicmean_17',['MillerIndexDynamicMean',['../syntax-models.html#millerindexdynamicmean',1,'']]],
  ['millerindexdynamicsum_18',['MillerIndexDynamicSum',['../syntax-models.html#millerindexdynamicsum',1,'']]],
  ['millerindexfromtorchscript_19',['MillerIndexFromTorchScript',['../syntax-tensors.html#millerindexfromtorchscript',1,'']]],
  ['millerindexinputparameter_20',['MillerIndexInputParameter',['../syntax-models.html#millerindexinputparameter',1,'']]],
  ['millerindexintermediatediff_21',['MillerIndexIntermediateDiff',['../syntax-models.html#millerindexintermediatediff',1,'']]],
  ['millerindexintermediatemean_22',['MillerIndexIntermediateMean',['../syntax-models.html#millerindexintermediatemean',1,'']]],
  ['millerindexintermediatesum_23',['MillerIndexIntermediateSum',['../syntax-models.html#millerindexintermediatesum',1,'']]],
  ['millerindexparametertovariable_24',['MillerIndexParameterToVariable',['../syntax-models.html#millerindexparametertovariable',1,'']]],
  ['mixed_20hardening_25',['Mixed hardening',['../solid-mechanics.html#autotoc_md58',1,'']]],
  ['mixed_20stress_20strain_20control_26',['Mixed stress/strain control',['../solid-mechanics.html#autotoc_md60',1,'']]],
  ['mixedcontrolsetup_27',['MixedControlSetup',['../syntax-models.html#mixedcontrolsetup',1,'']]],
  ['model_28',['Model',['../system-models.html',1,'']]],
  ['model_29',['model',['../python-examples-deterministic.html#autotoc_md189',1,'Actually setup the model'],['../python-examples-statistical.html#autotoc_md227',1,'Actually setup the model'],['../python-examples-statistical.html#autotoc_md235',1,'Convert the model to a hierarchical statistical model'],['../tutorials-models-running-your-first-model.html#autotoc_md150',1,'Evaluating the model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md174',1,'Extract the orientations for the multiplicative model'],['../tutorials-models-implicit-model.html',1,'Implicit model'],['../tutorials-getting-started.html#autotoc_md114',1,'Loading a model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md171',1,'ODF reconstruction for the seperated model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md172',1,'pyzag driver for the integrated model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md169',1,'pyzag driver for the separated model'],['../tutorials-models-running-your-first-model.html',1,'Running your first model'],['../python-examples-deterministic.html#autotoc_md185',1,'Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model'],['../python-examples-statistical.html#autotoc_md222',1,'Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model'],['../python-examples-deterministic.html#autotoc_md188',1,'Setup the actual model'],['../python-examples-statistical.html#autotoc_md226',1,'Setup the actual model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md173',1,'Simulate for the multiplicative model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md170',1,'Simulate rolling deformation for the seperated model']]],
  ['model_20against_20the_20synthetic_20data_30',['Calibrate the model against the synthetic data',['../python-examples-deterministic.html#autotoc_md197',1,'']]],
  ['model_20assembly_31',['Model assembly',['../system-models.html#model-assembly',1,'']]],
  ['model_20based_20nonlinear_20system_32',['Model-based nonlinear system',['../system-equationsystems.html#autotoc_md80',1,'']]],
  ['model_20building_20blocks_33',['Finite volume transport model building blocks',['../finite-volume.html#autotoc_md37',1,'']]],
  ['model_20calibration_34',['Deterministic material model calibration',['../python-examples-deterministic.html',1,'']]],
  ['model_20coefficients_35',['Print the calibrated model coefficients',['../python-examples-deterministic.html#autotoc_md199',1,'']]],
  ['model_20composition_36',['Model composition',['../tutorials-extension-model-composition.html',1,'Model composition'],['../tutorials-models-model-composition.html',1,'Model composition'],['../system-models.html#model-composition',1,'Model composition']]],
  ['model_20definition_37',['Model definition',['../system-models.html#model-definition',1,'Model definition'],['../tutorials-optimization-automatic-differentiation.html#autotoc_md161',1,'Model definition']]],
  ['model_20development_38',['Model development',['../tutorials-contributing.html#autotoc_md90',1,'']]],
  ['model_20for_20training_39',['model for training',['../python-examples-deterministic.html#autotoc_md194',1,'Setup the model for training'],['../python-examples-statistical.html#autotoc_md233',1,'Setup the model for training']]],
  ['model_20from_20the_20input_20file_40',['Loading a model from the input file',['../tutorials-models-running-your-first-model.html#autotoc_md148',1,'']]],
  ['model_20inspection_41',['Model inspection',['../tutorials-extension-argument-declaration.html#autotoc_md98',1,'']]],
  ['model_20learning_42',['Statistical material model learning',['../python-examples-statistical.html',1,'']]],
  ['model_20library_20version_202_43',['The New Engineering Material model Library, version 2',['../index.html#autotoc_md1',1,'']]],
  ['model_20on_20a_20different_20device_44',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md120',1,'']]],
  ['model_20parameters_45',['Model parameters',['../tutorials-models-model-parameters.html',1,'']]],
  ['model_20parameters_46',['model parameters',['../python-examples-deterministic.html#autotoc_md195',1,'Scale the model parameters'],['../python-examples-statistical.html#autotoc_md234',1,'Scale the model parameters']]],
  ['model_20parameters_20revisited_47',['Model parameters (revisited)',['../tutorials-models-model-parameters-revisited.html',1,'']]],
  ['model_20parameters_20with_20random_20values_48',['model parameters with random values',['../python-examples-deterministic.html#autotoc_md191',1,'Replace the model parameters with random values'],['../python-examples-statistical.html#autotoc_md229',1,'Replace the model parameters with random values']]],
  ['model_20predictions_49',['Plot the calibrated model predictions',['../python-examples-deterministic.html#autotoc_md198',1,'']]],
  ['model_20results_50',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md175',1,'']]],
  ['model_20structure_51',['Model structure',['../tutorials-models-just-in-time-compilation.html#autotoc_md127',1,'']]],
  ['model_20structure_20and_20forward_20operators_52',['Model structure and forward operators',['../tutorials-models-running-your-first-model.html#autotoc_md149',1,'']]],
  ['model_20to_20a_20hierarchical_20statistical_20model_53',['Convert the model to a hierarchical statistical model',['../python-examples-statistical.html#autotoc_md235',1,'']]],
  ['model_20to_20compare_20to_20the_20repeated_20test_54',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md236',1,'']]],
  ['model_20to_20generate_20the_20synthetic_20data_55',['model to generate the synthetic data',['../python-examples-deterministic.html#autotoc_md192',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md230',1,'Run the model to generate the synthetic data']]],
  ['model_20with_20the_20initial_20parameter_20values_56',['Run the model with the initial parameter values',['../python-examples-deterministic.html#autotoc_md196',1,'']]],
  ['models_57',['Models',['../syntax-models.html',1,'[Models]'],['../tutorials-models.html',1,'Models']]],
  ['models_58',['models',['../tutorials-extension.html#autotoc_md104',1,'Seaching for available models'],['../tutorials-models-running-your-first-model.html#autotoc_md145',1,'Searching for available models']]],
  ['models_3a_20the_20easy_20way_59',['Evaluating the models: The easy way',['../tutorials-models-model-composition.html#autotoc_md134',1,'']]],
  ['models_3a_20the_20hard_20way_60',['Evaluating the models: The hard way',['../tutorials-models-model-composition.html#autotoc_md133',1,'']]],
  ['modifying_20parameter_20values_61',['Modifying parameter values',['../tutorials-getting-started.html#autotoc_md116',1,'']]],
  ['moved_20from_20transientdriver_20into_20implicitupdate_62',['Predictor moved from &lt;span class=&quot;tt&quot;&gt;TransientDriver&lt;/span&gt; into &lt;span class=&quot;tt&quot;&gt;ImplicitUpdate&lt;/span&gt;',['../migration-211-212.html#predictor-migration',1,'']]],
  ['multicolumncsvscalar_63',['MultiColumnCSVScalar',['../syntax-tensors.html#multicolumncsvscalar',1,'']]],
  ['multiplicative_20model_64',['multiplicative model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md174',1,'Extract the orientations for the multiplicative model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md173',1,'Simulate for the multiplicative model']]],
  ['multiplicative_20model_20results_65',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md175',1,'']]],
  ['my_20data_66',['Who touched my data?',['../tutorials-tensors-tensor-view.html#autotoc_md253',1,'']]]
];
