var searchData=
[
  ['objects_20and_20their_20input_20file_20syntax_0',['objects and their input file syntax',['../syntax-data.html#autotoc_md67',1,'Available objects and their input file syntax'],['../syntax-drivers.html#autotoc_md68',1,'Available objects and their input file syntax'],['../syntax-equationsystems.html#autotoc_md69',1,'Available objects and their input file syntax'],['../syntax-models.html#autotoc_md70',1,'Available objects and their input file syntax'],['../syntax-schedulers.html#autotoc_md71',1,'Available objects and their input file syntax'],['../syntax-settings.html#autotoc_md72',1,'Available objects and their input file syntax'],['../syntax-solvers.html#autotoc_md73',1,'Available objects and their input file syntax'],['../syntax-tensors.html#autotoc_md74',1,'Available objects and their input file syntax']]],
  ['obtaining_20parameter_20derivatives_20of_20recursive_20nonlinear_20functions_1',['Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions',['../tutorials-optimization-pyzag.html#autotoc_md165',1,'']]],
  ['odf_20for_20the_20multiplicative_20model_20results_2',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md175',1,'']]],
  ['odf_20reconstruction_3',['ODF reconstruction',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md183',1,'']]],
  ['odf_20reconstruction_20for_20the_20seperated_20model_4',['ODF reconstruction for the seperated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md171',1,'']]],
  ['of_20dependencies_5',['List of dependencies',['../dependency-management.html#autotoc_md9',1,'']]],
  ['of_20equations_6',['of equations',['../tutorials-models-implicit-model.html#autotoc_md122',1,'Defining the system of equations'],['../tutorials-models-implicit-model.html#autotoc_md123',1,'Solving the system of equations']]],
  ['of_20notable_20parameters_7',['Physical meaning of notable parameters',['../python-examples-explain.html#autotoc_md216',1,'']]],
  ['of_20recursive_20nonlinear_20functions_8',['Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions',['../tutorials-optimization-pyzag.html#autotoc_md165',1,'']]],
  ['of_20the_20elastic_20strains_9',['Plot some comparisons of the elastic strains',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md177',1,'']]],
  ['olevskysinteringstress_10',['OlevskySinteringStress',['../syntax-models.html#olevskysinteringstress',1,'']]],
  ['on_20a_20different_20device_11',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md120',1,'']]],
  ['on_20the_20implicit_20function_20theorem_12',['Remarks on the implicit function theorem',['../tutorials-models-implicit-model.html#autotoc_md124',1,'']]],
  ['one_20sentence_13',['In one sentence',['../python-examples-explain.html#autotoc_md221',1,'']]],
  ['operator_14',['The forward operator',['../tutorials-extension-the-forward-operator.html',1,'']]],
  ['operators_15',['operators',['../tutorials-getting-started.html#autotoc_md115',1,'Calling forward operators'],['../tutorials-models-running-your-first-model.html#autotoc_md149',1,'Model structure and forward operators']]],
  ['optimization_16',['Optimization',['../tutorials-optimization.html',1,'']]],
  ['optimization_17',['JIT optimization',['../tutorials-models-just-in-time-compilation.html#autotoc_md129',1,'']]],
  ['optional_20scheduler_20hookup_20in_20drivers_18',['Optional scheduler hookup in drivers',['../migration-200-210.html#autotoc_md21',1,'']]],
  ['options_19',['options',['../build-customization.html#autotoc_md5',1,'Configure options'],['../migration-200-210.html#autotoc_md27',1,'Integration options']]],
  ['orientation_20',['Orientation',['../syntax-tensors.html#orientation',1,'']]],
  ['orientationrate_21',['OrientationRate',['../syntax-models.html#orientationrate',1,'']]],
  ['orientations_20for_20the_20multiplicative_20model_22',['Extract the orientations for the multiplicative model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md174',1,'']]],
  ['our_20initial_20guess_20at_20the_20parameters_23',['our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['our_20repeated_20case_24',['Go back and sample our repeated case',['../python-examples-statistical.html#autotoc_md239',1,'']]],
  ['outline_25',['Outline',['../tutorials-extension.html#autotoc_md105',1,'']]],
  ['output_20identification_26',['Automatic input/output identification',['../system-models.html#automatic-input-output-identification',1,'']]],
  ['overall_20workflow_27',['Overall workflow',['../python-examples-explain.html#autotoc_md200',1,'']]],
  ['overview_28',['Overview',['../index.html#autotoc_md0',1,'']]]
];
