var searchData=
[
  ['factory_0',['Factory',['../tutorials-extension-connection-to-input-files.html#autotoc_md102',1,'']]],
  ['factory_20methods_1',['Factory methods',['../tutorials-tensors-tensor-creation.html#autotoc_md248',1,'']]],
  ['fbcomplementarity_2',['FBComplementarity',['../syntax-models.html#fbcomplementarity',1,'']]],
  ['features_3',['features',['../python-examples-explain.html#autotoc_md217',1,'Assumptions, limitations, and special features'],['../python-examples-explain.html#autotoc_md220',1,'Special features']]],
  ['features_20and_20design_20philosophy_4',['Features and design philosophy',['../index.html#autotoc_md3',1,'']]],
  ['fetchcontent_5',['FetchContent',['../external-project-integration.html#autotoc_md17',1,'']]],
  ['field_20fracture_6',['Phase-Field Fracture',['../phase-field-fracture.html',1,'']]],
  ['figure_7',['figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md182',1,'Plot a discrete inverse pole figure'],['../python-examples-crystal_plasticity-polefigures.html#autotoc_md181',1,'Plot a discrete pole figure']]],
  ['figures_8',['Plot the pole figures',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md176',1,'']]],
  ['file_9',['Example Input File',['../thermosetting-pyrolysis.html#autotoc_md66',1,'']]],
  ['file_10',['file',['../reactive-infiltration.html#autotoc_md47',1,'Complete input file'],['../tutorials-models-input-file.html',1,'Input file'],['../tutorials-extension-connection-to-input-files.html#autotoc_md100',1,'Input file'],['../tutorials-extension-model-composition.html#autotoc_md107',1,'Input file'],['../tutorials-models-running-your-first-model.html#autotoc_md148',1,'Loading a model from the input file'],['../tutorials-models-model-composition.html#autotoc_md132',1,'Writing the input file'],['../tutorials-models-running-your-first-model.html#autotoc_md146',1,'Writing the input file']]],
  ['file_20changes_11',['file changes',['../migration-200-210.html#autotoc_md19',1,'Input file changes'],['../migration-211-212.html#autotoc_md29',1,'Input file changes']]],
  ['file_20in_20natural_20language_12',['Use LLM to explain NEML2 input file in natural language',['../python-examples-explain.html',1,'']]],
  ['file_20syntax_13',['file syntax',['../syntax-data.html#autotoc_md67',1,'Available objects and their input file syntax'],['../syntax-drivers.html#autotoc_md68',1,'Available objects and their input file syntax'],['../syntax-equationsystems.html#autotoc_md69',1,'Available objects and their input file syntax'],['../syntax-models.html#autotoc_md70',1,'Available objects and their input file syntax'],['../syntax-schedulers.html#autotoc_md71',1,'Available objects and their input file syntax'],['../syntax-settings.html#autotoc_md72',1,'Available objects and their input file syntax'],['../syntax-solvers.html#autotoc_md73',1,'Available objects and their input file syntax'],['../syntax-tensors.html#autotoc_md74',1,'Available objects and their input file syntax']]],
  ['files_14',['Connection to input files',['../tutorials-extension-connection-to-input-files.html',1,'']]],
  ['fillr2_15',['FillR2',['../syntax-tensors.html#fillr2',1,'']]],
  ['fillrot_16',['FillRot',['../syntax-tensors.html#fillrot',1,'']]],
  ['fillsr2_17',['FillSR2',['../syntax-tensors.html#fillsr2',1,'']]],
  ['fillwr2_18',['FillWR2',['../syntax-tensors.html#fillwr2',1,'']]],
  ['find_5fpackage_19',['find_package',['../external-project-integration.html#autotoc_md18',1,'']]],
  ['finite_20volume_20',['Finite Volume',['../finite-volume.html',1,'']]],
  ['finite_20volume_20discretization_21',['Finite volume discretization',['../finite-volume.html#autotoc_md33',1,'']]],
  ['finite_20volume_20transport_20model_20building_20blocks_22',['Finite volume transport model building blocks',['../finite-volume.html#autotoc_md37',1,'']]],
  ['finitevolumeappendboundarycondition_23',['FiniteVolumeAppendBoundaryCondition',['../syntax-models.html#finitevolumeappendboundarycondition',1,'']]],
  ['finitevolumegradient_24',['FiniteVolumeGradient',['../syntax-models.html#finitevolumegradient',1,'']]],
  ['finitevolumeupwindedadvectiveflux_25',['FiniteVolumeUpwindedAdvectiveFlux',['../syntax-models.html#finitevolumeupwindedadvectiveflux',1,'']]],
  ['first_20model_26',['Running your first model',['../tutorials-models-running-your-first-model.html',1,'']]],
  ['fixed_20condition_27',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md232',1,'']]],
  ['fixorientation_28',['FixOrientation',['../syntax-models.html#fixorientation',1,'']]],
  ['flow_20direction_3a_20associative_20plasticity_29',['5. Flow direction: associative plasticity',['../python-examples-explain.html#autotoc_md211',1,'']]],
  ['flow_20rules_30',['Flow rules',['../solid-mechanics.html#autotoc_md59',1,'']]],
  ['flow_20rules_31',['6. Rate-independent and rate-dependent flow rules',['../python-examples-explain.html#autotoc_md212',1,'']]],
  ['flux_32',['Advective flux',['../finite-volume.html#autotoc_md36',1,'']]],
  ['for_20available_20models_33',['for available models',['../tutorials-extension.html#autotoc_md104',1,'Seaching for available models'],['../tutorials-models-running-your-first-model.html#autotoc_md145',1,'Searching for available models']]],
  ['for_20loop_34',['For loop',['../tutorials-models-vectorization.html#autotoc_md155',1,'']]],
  ['for_20loop_20versus_20vectorization_3a_20a_20numerical_20experiment_35',['For loop versus vectorization: A numerical experiment',['../tutorials-models-vectorization.html#autotoc_md154',1,'']]],
  ['for_20our_20initial_20guess_20at_20the_20parameters_36',['for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['for_20the_20integrated_20model_37',['pyzag driver for the integrated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md172',1,'']]],
  ['for_20the_20multiplicative_20model_38',['for the multiplicative model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md174',1,'Extract the orientations for the multiplicative model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md173',1,'Simulate for the multiplicative model']]],
  ['for_20the_20multiplicative_20model_20results_39',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md175',1,'']]],
  ['for_20the_20repeated_20experiment_40',['Conditions for the repeated experiment',['../python-examples-statistical.html#autotoc_md224',1,'']]],
  ['for_20the_20separated_20model_41',['pyzag driver for the separated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md169',1,'']]],
  ['for_20the_20seperated_20model_42',['for the seperated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md171',1,'ODF reconstruction for the seperated model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md170',1,'Simulate rolling deformation for the seperated model']]],
  ['for_20training_43',['for training',['../python-examples-deterministic.html#autotoc_md194',1,'Setup the model for training'],['../python-examples-statistical.html#autotoc_md233',1,'Setup the model for training']]],
  ['formatting_20and_20static_20analysis_44',['Code formatting and static analysis',['../tutorials-contributing.html#autotoc_md95',1,'']]],
  ['formulations_45',['Crystal plasticity formulations',['../python-examples-crystal_plasticity-compare_formulations.html',1,'']]],
  ['forward_20operator_46',['The forward operator',['../tutorials-extension-the-forward-operator.html',1,'']]],
  ['forward_20operators_47',['forward operators',['../tutorials-getting-started.html#autotoc_md115',1,'Calling forward operators'],['../tutorials-models-running-your-first-model.html#autotoc_md149',1,'Model structure and forward operators']]],
  ['fracture_48',['Phase-Field Fracture',['../phase-field-fracture.html',1,'']]],
  ['framework_49',['Framework',['../thermosetting-pyrolysis.html#autotoc_md62',1,'']]],
  ['fredrickarmstrongplastichardening_50',['FredrickArmstrongPlasticHardening',['../syntax-models.html#fredrickarmstrongplastichardening',1,'']]],
  ['from_20kocks–mecking_20scaling_51',['2. Yield stress from Kocks–Mecking scaling',['../python-examples-explain.html#autotoc_md208',1,'']]],
  ['from_20the_20input_20file_52',['Loading a model from the input file',['../tutorials-models-running-your-first-model.html#autotoc_md148',1,'']]],
  ['from_20transientdriver_20into_20implicitupdate_53',['Predictor moved from &lt;span class=&quot;tt&quot;&gt;TransientDriver&lt;/span&gt; into &lt;span class=&quot;tt&quot;&gt;ImplicitUpdate&lt;/span&gt;',['../migration-211-212.html#predictor-migration',1,'']]],
  ['from_20v2_200_200_20to_20v2_201_200_54',['Migrating from v2.0.0 to v2.1.0',['../migration-200-210.html',1,'']]],
  ['from_20v2_201_201_20to_20v2_201_202_55',['Migrating from v2.1.1 to v2.1.2',['../migration-211-212.html',1,'']]],
  ['frontend_56',['Choosing the frontend',['../tutorials-models-running-your-first-model.html#autotoc_md147',1,'']]],
  ['fullmillerindex_57',['FullMillerIndex',['../syntax-tensors.html#fullmillerindex',1,'']]],
  ['fullquaternion_58',['FullQuaternion',['../syntax-tensors.html#fullquaternion',1,'']]],
  ['fullr2_59',['FullR2',['../syntax-tensors.html#fullr2',1,'']]],
  ['fullr3_60',['FullR3',['../syntax-tensors.html#fullr3',1,'']]],
  ['fullr4_61',['FullR4',['../syntax-tensors.html#fullr4',1,'']]],
  ['fullrot_62',['FullRot',['../syntax-tensors.html#fullrot',1,'']]],
  ['fullscalar_63',['FullScalar',['../syntax-tensors.html#fullscalar',1,'']]],
  ['fullsffr4_64',['FullSFFR4',['../syntax-tensors.html#fullsffr4',1,'']]],
  ['fullsfr3_65',['FullSFR3',['../syntax-tensors.html#fullsfr3',1,'']]],
  ['fullsr2_66',['FullSR2',['../syntax-tensors.html#fullsr2',1,'']]],
  ['fullssr4_67',['FullSSR4',['../syntax-tensors.html#fullssr4',1,'']]],
  ['fullswr4_68',['FullSWR4',['../syntax-tensors.html#fullswr4',1,'']]],
  ['fulltensor_69',['FullTensor',['../syntax-tensors.html#fulltensor',1,'']]],
  ['fullvec_70',['FullVec',['../syntax-tensors.html#fullvec',1,'']]],
  ['fullwffr4_71',['FullWFFR4',['../syntax-tensors.html#fullwffr4',1,'']]],
  ['fullwr2_72',['FullWR2',['../syntax-tensors.html#fullwr2',1,'']]],
  ['fullwsr4_73',['FullWSR4',['../syntax-tensors.html#fullwsr4',1,'']]],
  ['fullwwr4_74',['FullWWR4',['../syntax-tensors.html#fullwwr4',1,'']]],
  ['function_75',['function',['../python-examples-explain.html#autotoc_md210',1,'4. Yield function'],['../solid-mechanics.html#autotoc_md54',1,'Perfectly Plastic Yield function']]],
  ['function_20theorem_76',['Remarks on the implicit function theorem',['../tutorials-models-implicit-model.html#autotoc_md124',1,'']]],
  ['functions_77',['functions',['../tutorials-optimization-pyzag.html#autotoc_md165',1,'Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions'],['../phase-field-fracture.html#autotoc_md40',1,'Crack geometric functions'],['../phase-field-fracture.html#autotoc_md41',1,'Degradation functions']]]
];
