var searchData=
[
  ['r2_0',['R2',['../syntax-tensors.html#r2',1,'']]],
  ['r2backwardeulertimeintegration_1',['R2BackwardEulerTimeIntegration',['../syntax-models.html#r2backwardeulertimeintegration',1,'']]],
  ['r2constantparameter_2',['R2ConstantParameter',['../syntax-models.html#r2constantparameter',1,'']]],
  ['r2determinant_3',['R2Determinant',['../syntax-models.html#r2determinant',1,'']]],
  ['r2dynamicmean_4',['R2DynamicMean',['../syntax-models.html#r2dynamicmean',1,'']]],
  ['r2dynamicsum_5',['R2DynamicSum',['../syntax-models.html#r2dynamicsum',1,'']]],
  ['r2fromtorchscript_6',['R2FromTorchScript',['../syntax-tensors.html#r2fromtorchscript',1,'']]],
  ['r2inputparameter_7',['R2InputParameter',['../syntax-models.html#r2inputparameter',1,'']]],
  ['r2intermediatediff_8',['R2IntermediateDiff',['../syntax-models.html#r2intermediatediff',1,'']]],
  ['r2intermediatemean_9',['R2IntermediateMean',['../syntax-models.html#r2intermediatemean',1,'']]],
  ['r2intermediatesum_10',['R2IntermediateSum',['../syntax-models.html#r2intermediatesum',1,'']]],
  ['r2linearcombination_11',['R2LinearCombination',['../syntax-models.html#r2linearcombination',1,'']]],
  ['r2multiplication_12',['R2Multiplication',['../syntax-models.html#r2multiplication',1,'']]],
  ['r2parametertovariable_13',['R2ParameterToVariable',['../syntax-models.html#r2parametertovariable',1,'']]],
  ['r2tosr2_14',['R2ToSR2',['../syntax-models.html#r2tosr2',1,'']]],
  ['r2towr2_15',['R2ToWR2',['../syntax-models.html#r2towr2',1,'']]],
  ['r2variablerate_16',['R2VariableRate',['../syntax-models.html#r2variablerate',1,'']]],
  ['r3_17',['R3',['../syntax-tensors.html#r3',1,'']]],
  ['r3constantparameter_18',['R3ConstantParameter',['../syntax-models.html#r3constantparameter',1,'']]],
  ['r3dynamicmean_19',['R3DynamicMean',['../syntax-models.html#r3dynamicmean',1,'']]],
  ['r3dynamicsum_20',['R3DynamicSum',['../syntax-models.html#r3dynamicsum',1,'']]],
  ['r3fromtorchscript_21',['R3FromTorchScript',['../syntax-tensors.html#r3fromtorchscript',1,'']]],
  ['r3inputparameter_22',['R3InputParameter',['../syntax-models.html#r3inputparameter',1,'']]],
  ['r3intermediatediff_23',['R3IntermediateDiff',['../syntax-models.html#r3intermediatediff',1,'']]],
  ['r3intermediatemean_24',['R3IntermediateMean',['../syntax-models.html#r3intermediatemean',1,'']]],
  ['r3intermediatesum_25',['R3IntermediateSum',['../syntax-models.html#r3intermediatesum',1,'']]],
  ['r3parametertovariable_26',['R3ParameterToVariable',['../syntax-models.html#r3parametertovariable',1,'']]],
  ['r4_27',['R4',['../syntax-tensors.html#r4',1,'']]],
  ['r4constantparameter_28',['R4ConstantParameter',['../syntax-models.html#r4constantparameter',1,'']]],
  ['r4dynamicmean_29',['R4DynamicMean',['../syntax-models.html#r4dynamicmean',1,'']]],
  ['r4dynamicsum_30',['R4DynamicSum',['../syntax-models.html#r4dynamicsum',1,'']]],
  ['r4fromtorchscript_31',['R4FromTorchScript',['../syntax-tensors.html#r4fromtorchscript',1,'']]],
  ['r4inputparameter_32',['R4InputParameter',['../syntax-models.html#r4inputparameter',1,'']]],
  ['r4intermediatediff_33',['R4IntermediateDiff',['../syntax-models.html#r4intermediatediff',1,'']]],
  ['r4intermediatemean_34',['R4IntermediateMean',['../syntax-models.html#r4intermediatemean',1,'']]],
  ['r4intermediatesum_35',['R4IntermediateSum',['../syntax-models.html#r4intermediatesum',1,'']]],
  ['r4parametertovariable_36',['R4ParameterToVariable',['../syntax-models.html#r4parametertovariable',1,'']]],
  ['random_20values_37',['random values',['../python-examples-deterministic.html#autotoc_md191',1,'Replace the model parameters with random values'],['../python-examples-statistical.html#autotoc_md229',1,'Replace the model parameters with random values']]],
  ['randommillerindex_38',['RandomMillerIndex',['../syntax-tensors.html#randommillerindex',1,'']]],
  ['randomquaternion_39',['RandomQuaternion',['../syntax-tensors.html#randomquaternion',1,'']]],
  ['randomr2_40',['RandomR2',['../syntax-tensors.html#randomr2',1,'']]],
  ['randomr3_41',['RandomR3',['../syntax-tensors.html#randomr3',1,'']]],
  ['randomr4_42',['RandomR4',['../syntax-tensors.html#randomr4',1,'']]],
  ['randomrot_43',['RandomRot',['../syntax-tensors.html#randomrot',1,'']]],
  ['randomscalar_44',['RandomScalar',['../syntax-tensors.html#randomscalar',1,'']]],
  ['randomsffr4_45',['RandomSFFR4',['../syntax-tensors.html#randomsffr4',1,'']]],
  ['randomsfr3_46',['RandomSFR3',['../syntax-tensors.html#randomsfr3',1,'']]],
  ['randomsr2_47',['RandomSR2',['../syntax-tensors.html#randomsr2',1,'']]],
  ['randomssr4_48',['RandomSSR4',['../syntax-tensors.html#randomssr4',1,'']]],
  ['randomswr4_49',['RandomSWR4',['../syntax-tensors.html#randomswr4',1,'']]],
  ['randomtensor_50',['RandomTensor',['../syntax-tensors.html#randomtensor',1,'']]],
  ['randomvec_51',['RandomVec',['../syntax-tensors.html#randomvec',1,'']]],
  ['randomwffr4_52',['RandomWFFR4',['../syntax-tensors.html#randomwffr4',1,'']]],
  ['randomwr2_53',['RandomWR2',['../syntax-tensors.html#randomwr2',1,'']]],
  ['randomwsr4_54',['RandomWSR4',['../syntax-tensors.html#randomwsr4',1,'']]],
  ['randomwwr4_55',['RandomWWR4',['../syntax-tensors.html#randomwwr4',1,'']]],
  ['rate_20dependent_20flow_20rules_56',['6. Rate-independent and rate-dependent flow rules',['../python-examples-explain.html#autotoc_md212',1,'']]],
  ['rate_20independent_20and_20rate_20dependent_20flow_20rules_57',['6. Rate-independent and rate-dependent flow rules',['../python-examples-explain.html#autotoc_md212',1,'']]],
  ['rationaldegradationfunction_58',['RationalDegradationFunction',['../syntax-models.html#rationaldegradationfunction',1,'']]],
  ['reaction_20kinetics_59',['Reaction kinetics',['../thermosetting-pyrolysis.html#autotoc_md63',1,'']]],
  ['reaction_20mechanisms_60',['Reaction mechanisms',['../chemical-reactions.html#autotoc_md30',1,'']]],
  ['reactions_61',['Chemical Reactions',['../chemical-reactions.html',1,'']]],
  ['reactive_20infiltration_62',['Reactive Infiltration',['../reactive-infiltration.html',1,'']]],
  ['reconstruction_63',['ODF reconstruction',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md183',1,'']]],
  ['reconstruction_20for_20the_20seperated_20model_64',['ODF reconstruction for the seperated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md171',1,'']]],
  ['recursive_20nonlinear_20functions_65',['Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions',['../tutorials-optimization-pyzag.html#autotoc_md165',1,'']]],
  ['reference_20a_20linear_20solver_66',['Nonlinear solvers now reference a linear solver',['../migration-200-210.html#linear_solver',1,'']]],
  ['registration_67',['Automatic dependency registration',['../system-models.html#automatic-dependency-registration',1,'']]],
  ['registry_68',['Registry',['../tutorials-extension-connection-to-input-files.html#autotoc_md101',1,'']]],
  ['regression_20tests_69',['Regression tests',['../tutorials-contributing.html#testing-regression-tests',1,'']]],
  ['regression_20tests_70',['Verification and regression tests',['../finite-volume.html#autotoc_md39',1,'']]],
  ['related_20to_20how_20we_20calibrate_20the_20model_71',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model',['../python-examples-deterministic.html#autotoc_md185',1,'']]],
  ['related_20to_20how_20we_20train_20the_20model_72',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model',['../python-examples-statistical.html#autotoc_md222',1,'']]],
  ['remarks_73',['Remarks',['../tutorials-models-vectorization.html#autotoc_md157',1,'']]],
  ['remarks_20on_20the_20implicit_20function_20theorem_74',['Remarks on the implicit function theorem',['../tutorials-models-implicit-model.html#autotoc_md124',1,'']]],
  ['removed_75',['removed',['../migration-211-212.html#sdt-ldi-removed',1,'&lt;span class=&quot;tt&quot;&gt;SDTSolidMechanicsDriver&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;LDISolidMechanicsDriver&lt;/span&gt; removed'],['../migration-211-212.html#variable-naming',1,'Variable naming: subspace prefixes removed']]],
  ['renamed_20n_20suffix_76',['History variables renamed (&lt;span class=&quot;tt&quot;&gt;~N&lt;/span&gt; suffix)',['../migration-211-212.html#history-naming',1,'']]],
  ['repeated_20case_77',['Go back and sample our repeated case',['../python-examples-statistical.html#autotoc_md239',1,'']]],
  ['repeated_20experiment_78',['Conditions for the repeated experiment',['../python-examples-statistical.html#autotoc_md224',1,'']]],
  ['repeated_20test_79',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md236',1,'']]],
  ['replace_20the_20model_20parameters_20with_20random_20values_80',['Replace the model parameters with random values',['../python-examples-deterministic.html#autotoc_md191',1,'Replace the model parameters with random values'],['../python-examples-statistical.html#autotoc_md229',1,'Replace the model parameters with random values']]],
  ['representative_20volume_20element_81',['Representative Volume Element',['../reactive-infiltration.html#autotoc_md44',1,'']]],
  ['required_82',['&lt;span class=&quot;tt&quot;&gt;NonlinearSystem&lt;/span&gt;: &lt;span class=&quot;tt&quot;&gt;unknowns&lt;/span&gt; is now required',['../migration-211-212.html#nonlinearsystem-unknowns',1,'']]],
  ['required_20libraries_20and_20setting_20up_83',['required libraries and setting up',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md168',1,'Importing required libraries and setting up'],['../python-examples-crystal_plasticity-polefigures.html#autotoc_md178',1,'Importing required libraries and setting up']]],
  ['resolution_84',['Automatic dependency resolution',['../system-models.html#automatic-dependency-resolution',1,'']]],
  ['resolvedshear_85',['ResolvedShear',['../syntax-models.html#resolvedshear',1,'']]],
  ['results_86',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md175',1,'']]],
  ['retrieving_20the_20parameter_20value_87',['Retrieving the parameter value',['../tutorials-models-model-parameters.html#autotoc_md137',1,'']]],
  ['revisited_88',['Model parameters (revisited)',['../tutorials-models-model-parameters-revisited.html',1,'']]],
  ['rolling_20deformation_89',['Simulate rolling deformation',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md180',1,'']]],
  ['rolling_20deformation_20for_20the_20seperated_20model_90',['Simulate rolling deformation for the seperated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md170',1,'']]],
  ['rot_91',['Rot',['../syntax-tensors.html#rot',1,'']]],
  ['rotationmatrix_92',['RotationMatrix',['../syntax-models.html#rotationmatrix',1,'']]],
  ['rotconstantparameter_93',['RotConstantParameter',['../syntax-models.html#rotconstantparameter',1,'']]],
  ['rotdynamicmean_94',['RotDynamicMean',['../syntax-models.html#rotdynamicmean',1,'']]],
  ['rotdynamicsum_95',['RotDynamicSum',['../syntax-models.html#rotdynamicsum',1,'']]],
  ['rotfromtorchscript_96',['RotFromTorchScript',['../syntax-tensors.html#rotfromtorchscript',1,'']]],
  ['rotinputparameter_97',['RotInputParameter',['../syntax-models.html#rotinputparameter',1,'']]],
  ['rotintermediatediff_98',['RotIntermediateDiff',['../syntax-models.html#rotintermediatediff',1,'']]],
  ['rotintermediatemean_99',['RotIntermediateMean',['../syntax-models.html#rotintermediatemean',1,'']]],
  ['rotintermediatesum_100',['RotIntermediateSum',['../syntax-models.html#rotintermediatesum',1,'']]],
  ['rotparametertovariable_101',['RotParameterToVariable',['../syntax-models.html#rotparametertovariable',1,'']]],
  ['rule_102',['Automatic chain rule',['../system-models.html#automatic-chain-rule',1,'']]],
  ['rules_103',['rules',['../python-examples-explain.html#autotoc_md212',1,'6. Rate-independent and rate-dependent flow rules'],['../solid-mechanics.html#autotoc_md59',1,'Flow rules'],['../tutorials-tensors-broadcasting.html#autotoc_md241',1,'NEML2&apos;s broadcasting rules']]],
  ['run_20at_20a_20fixed_20condition_104',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md232',1,'']]],
  ['run_20the_20model_20to_20generate_20the_20synthetic_20data_105',['Run the model to generate the synthetic data',['../python-examples-deterministic.html#autotoc_md192',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md230',1,'Run the model to generate the synthetic data']]],
  ['run_20the_20model_20with_20the_20initial_20parameter_20values_106',['Run the model with the initial parameter values',['../python-examples-deterministic.html#autotoc_md196',1,'']]],
  ['run_20the_20training_20loop_107',['Run the training loop',['../python-examples-statistical.html#autotoc_md238',1,'']]],
  ['running_20your_20first_20model_108',['Running your first model',['../tutorials-models-running-your-first-model.html',1,'']]]
];
