var searchData=
[
  ['easy_20way_0',['Evaluating the models: The easy way',['../tutorials-models-model-composition.html#autotoc_md134',1,'']]],
  ['edge_20interpolation_1',['Cell-edge interpolation',['../finite-volume.html#autotoc_md34',1,'']]],
  ['effective_20stress_2',['Effective stress',['../solid-mechanics.html#autotoc_md53',1,'']]],
  ['effective_20volume_3',['Effective volume',['../chemical-reactions.html#autotoc_md31',1,'']]],
  ['effectivesaturation_4',['EffectiveSaturation',['../syntax-models.html#effectivesaturation',1,'']]],
  ['effectivevolume_5',['EffectiveVolume',['../syntax-models.html#effectivevolume',1,'']]],
  ['elastic_20strains_6',['Plot some comparisons of the elastic strains',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md177',1,'']]],
  ['elasticity_7',['Elasticity',['../solid-mechanics.html#autotoc_md48',1,'']]],
  ['elasticity_20and_20strain_20decomposition_8',['Elasticity and strain decomposition',['../python-examples-explain.html#autotoc_md214',1,'']]],
  ['elasticstrainrate_9',['ElasticStrainRate',['../syntax-models.html#elasticstrainrate',1,'']]],
  ['element_10',['Representative Volume Element',['../reactive-infiltration.html#autotoc_md44',1,'']]],
  ['element_20indexing_11',['Single element indexing',['../tutorials-tensors-indexing.html#autotoc_md244',1,'']]],
  ['energy_20density_12',['Strain Energy Density',['../phase-field-fracture.html#autotoc_md42',1,'']]],
  ['engineering_20material_20model_20library_20version_202_13',['The New Engineering Material model Library, version 2',['../index.html#autotoc_md1',1,'']]],
  ['equation_20system_14',['Equation System',['../system-equationsystems.html',1,'']]],
  ['equations_15',['equations',['../tutorials-models-implicit-model.html#autotoc_md122',1,'Defining the system of equations'],['../reactive-infiltration.html#autotoc_md45',1,'Governing equations'],['../tutorials-models-implicit-model.html#autotoc_md123',1,'Solving the system of equations']]],
  ['equationsystems_16',['[EquationSystems]',['../syntax-equationsystems.html',1,'']]],
  ['equationsystems_20nonlinearsystem_17',['Migration to EquationSystems (&lt;span class=&quot;tt&quot;&gt;NonlinearSystem&lt;/span&gt;)',['../migration-200-210.html#eqsys',1,'']]],
  ['equivalent_20stress_18',['1. Stress measure and equivalent stress',['../python-examples-explain.html#autotoc_md207',1,'']]],
  ['evaluating_20the_20model_19',['Evaluating the model',['../tutorials-models-running-your-first-model.html#autotoc_md150',1,'']]],
  ['evaluating_20the_20model_20on_20a_20different_20device_20',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md120',1,'']]],
  ['evaluating_20the_20models_3a_20the_20easy_20way_21',['Evaluating the models: The easy way',['../tutorials-models-model-composition.html#autotoc_md134',1,'']]],
  ['evaluating_20the_20models_3a_20the_20hard_20way_22',['Evaluating the models: The hard way',['../tutorials-models-model-composition.html#autotoc_md133',1,'']]],
  ['evaluation_23',['Evaluation',['../tutorials-extension-the-forward-operator.html#autotoc_md111',1,'']]],
  ['evaluation_20device_24',['Evaluation device',['../tutorials-models-evaluation-device.html',1,'']]],
  ['event_20tracing_25',['Event tracing',['../system-schedulers.html#autotoc_md87',1,'']]],
  ['example_26',['Example',['../phase-field-fracture.html#autotoc_md43',1,'Example'],['../tutorials-tensors-broadcasting.html#autotoc_md242',1,'Example']]],
  ['example_27',['A symbolic example',['../system-models.html#a-symbolic-example',1,'']]],
  ['example_20input_20file_28',['Example Input File',['../thermosetting-pyrolysis.html#autotoc_md66',1,'']]],
  ['example_3a_20combined_20advection–diffusion–reaction_29',['Example: combined advection–diffusion–reaction',['../finite-volume.html#autotoc_md38',1,'']]],
  ['examples_30',['Examples',['../chemical-reactions.html#autotoc_md32',1,'']]],
  ['experiment_31',['experiment',['../python-examples-statistical.html#autotoc_md224',1,'Conditions for the repeated experiment'],['../tutorials-models-vectorization.html#autotoc_md154',1,'For loop versus vectorization: A numerical experiment']]],
  ['experimental_20conditions_32',['experimental conditions',['../python-examples-deterministic.html#autotoc_md186',1,'Setup the synthetic experimental conditions'],['../python-examples-statistical.html#autotoc_md223',1,'Setup the synthetic experimental conditions']]],
  ['explain_20neml2_20input_20file_20in_20natural_20language_33',['Use LLM to explain NEML2 input file in natural language',['../python-examples-explain.html',1,'']]],
  ['exponentiallawpermeability_34',['ExponentialLawPermeability',['../syntax-models.html#exponentiallawpermeability',1,'']]],
  ['extension_35',['Extension',['../tutorials-extension.html',1,'']]],
  ['external_20project_20integration_36',['External Project Integration',['../external-project-integration.html',1,'']]],
  ['extract_20the_20orientations_20for_20the_20multiplicative_20model_37',['Extract the orientations for the multiplicative model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md174',1,'']]],
  ['extract_20the_20syntax_20database_38',['Extract the syntax database',['../python-examples-explain.html#autotoc_md202',1,'']]]
];
