var searchData=
[
  ['language_0',['Use LLM to explain NEML2 input file in natural language',['../python-examples-explain.html',1,'']]],
  ['lauching_20the_20projectiles_1',['Lauching the projectiles',['../tutorials-extension-model-composition.html#autotoc_md108',1,'']]],
  ['layout_20components_2',['Installation layout/components',['../migration-200-210.html#autotoc_md26',1,'']]],
  ['ldisolidmechanicsdriver_20removed_3',['&lt;span class=&quot;tt&quot;&gt;SDTSolidMechanicsDriver&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;LDISolidMechanicsDriver&lt;/span&gt; removed',['../migration-211-212.html#sdt-ldi-removed',1,'']]],
  ['learning_4',['Statistical material model learning',['../python-examples-statistical.html',1,'']]],
  ['level_20picture_5',['High-level picture',['../python-examples-explain.html#autotoc_md205',1,'']]],
  ['level_20sections_6',['New top-level sections',['../migration-200-210.html#autotoc_md20',1,'']]],
  ['libraries_20and_20setting_20up_7',['libraries and setting up',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md168',1,'Importing required libraries and setting up'],['../python-examples-crystal_plasticity-polefigures.html#autotoc_md178',1,'Importing required libraries and setting up']]],
  ['library_20version_202_8',['The New Engineering Material model Library, version 2',['../index.html#autotoc_md1',1,'']]],
  ['limitations_9',['Limitations',['../tutorials-models-just-in-time-compilation.html#autotoc_md130',1,'Limitations'],['../python-examples-explain.html#autotoc_md219',1,'Limitations']]],
  ['limitations_20and_20special_20features_10',['Assumptions, limitations, and special features',['../python-examples-explain.html#autotoc_md217',1,'']]],
  ['line_20arguments_11',['Command-line arguments',['../tutorials-contributing.html#autotoc_md91',1,'']]],
  ['linear_20solver_12',['Nonlinear solvers now reference a linear solver',['../migration-200-210.html#linear_solver',1,'']]],
  ['linear_20system_20interface_13',['Linear system interface',['../system-equationsystems.html#autotoc_md78',1,'']]],
  ['lineardashpot_14',['LinearDashpot',['../syntax-models.html#lineardashpot',1,'']]],
  ['linearextrapolationpredictor_15',['LinearExtrapolationPredictor',['../syntax-models.html#linearextrapolationpredictor',1,'']]],
  ['linearisotropicelasticity_16',['LinearIsotropicElasticity',['../syntax-models.html#linearisotropicelasticity',1,'']]],
  ['linearisotropicelasticj2trialstressupdate_17',['LinearIsotropicElasticJ2TrialStressUpdate',['../syntax-models.html#linearisotropicelasticj2trialstressupdate',1,'']]],
  ['linearisotropichardening_18',['LinearIsotropicHardening',['../syntax-models.html#linearisotropichardening',1,'']]],
  ['linearisotropicstrainenergydensity_19',['LinearIsotropicStrainEnergyDensity',['../syntax-models.html#linearisotropicstrainenergydensity',1,'']]],
  ['linearkinematichardening_20',['LinearKinematicHardening',['../syntax-models.html#linearkinematichardening',1,'']]],
  ['linearlyinterpolatetocelledges_21',['LinearlyInterpolateToCellEdges',['../syntax-models.html#linearlyinterpolatetocelledges',1,'']]],
  ['linearsinglesliphardeningrule_22',['LinearSingleSlipHardeningRule',['../syntax-models.html#linearsinglesliphardeningrule',1,'']]],
  ['linspacemillerindex_23',['LinspaceMillerIndex',['../syntax-tensors.html#linspacemillerindex',1,'']]],
  ['linspacequaternion_24',['LinspaceQuaternion',['../syntax-tensors.html#linspacequaternion',1,'']]],
  ['linspacer2_25',['LinspaceR2',['../syntax-tensors.html#linspacer2',1,'']]],
  ['linspacer3_26',['LinspaceR3',['../syntax-tensors.html#linspacer3',1,'']]],
  ['linspacer4_27',['LinspaceR4',['../syntax-tensors.html#linspacer4',1,'']]],
  ['linspacerot_28',['LinspaceRot',['../syntax-tensors.html#linspacerot',1,'']]],
  ['linspacescalar_29',['LinspaceScalar',['../syntax-tensors.html#linspacescalar',1,'']]],
  ['linspacesffr4_30',['LinspaceSFFR4',['../syntax-tensors.html#linspacesffr4',1,'']]],
  ['linspacesfr3_31',['LinspaceSFR3',['../syntax-tensors.html#linspacesfr3',1,'']]],
  ['linspacesr2_32',['LinspaceSR2',['../syntax-tensors.html#linspacesr2',1,'']]],
  ['linspacessr4_33',['LinspaceSSR4',['../syntax-tensors.html#linspacessr4',1,'']]],
  ['linspaceswr4_34',['LinspaceSWR4',['../syntax-tensors.html#linspaceswr4',1,'']]],
  ['linspacetensor_35',['LinspaceTensor',['../syntax-tensors.html#linspacetensor',1,'']]],
  ['linspacevec_36',['LinspaceVec',['../syntax-tensors.html#linspacevec',1,'']]],
  ['linspacewffr4_37',['LinspaceWFFR4',['../syntax-tensors.html#linspacewffr4',1,'']]],
  ['linspacewr2_38',['LinspaceWR2',['../syntax-tensors.html#linspacewr2',1,'']]],
  ['linspacewsr4_39',['LinspaceWSR4',['../syntax-tensors.html#linspacewsr4',1,'']]],
  ['linspacewwr4_40',['LinspaceWWR4',['../syntax-tensors.html#linspacewwr4',1,'']]],
  ['list_20of_20dependencies_41',['List of dependencies',['../dependency-management.html#autotoc_md9',1,'']]],
  ['literal_42',['Plain numeric literal',['../tutorials-models-model-parameters-revisited.html#autotoc_md141',1,'']]],
  ['llm_20chat_20client_43',['Call the LLM chat client',['../python-examples-explain.html#autotoc_md204',1,'']]],
  ['llm_20to_20explain_20neml2_20input_20file_20in_20natural_20language_44',['Use LLM to explain NEML2 input file in natural language',['../python-examples-explain.html',1,'']]],
  ['loading_20a_20model_45',['Loading a model',['../tutorials-getting-started.html#autotoc_md114',1,'']]],
  ['loading_20a_20model_20from_20the_20input_20file_46',['Loading a model from the input file',['../tutorials-models-running-your-first-model.html#autotoc_md148',1,'']]],
  ['logspacemillerindex_47',['LogspaceMillerIndex',['../syntax-tensors.html#logspacemillerindex',1,'']]],
  ['logspacequaternion_48',['LogspaceQuaternion',['../syntax-tensors.html#logspacequaternion',1,'']]],
  ['logspacer2_49',['LogspaceR2',['../syntax-tensors.html#logspacer2',1,'']]],
  ['logspacer3_50',['LogspaceR3',['../syntax-tensors.html#logspacer3',1,'']]],
  ['logspacer4_51',['LogspaceR4',['../syntax-tensors.html#logspacer4',1,'']]],
  ['logspacerot_52',['LogspaceRot',['../syntax-tensors.html#logspacerot',1,'']]],
  ['logspacescalar_53',['LogspaceScalar',['../syntax-tensors.html#logspacescalar',1,'']]],
  ['logspacesffr4_54',['LogspaceSFFR4',['../syntax-tensors.html#logspacesffr4',1,'']]],
  ['logspacesfr3_55',['LogspaceSFR3',['../syntax-tensors.html#logspacesfr3',1,'']]],
  ['logspacesr2_56',['LogspaceSR2',['../syntax-tensors.html#logspacesr2',1,'']]],
  ['logspacessr4_57',['LogspaceSSR4',['../syntax-tensors.html#logspacessr4',1,'']]],
  ['logspaceswr4_58',['LogspaceSWR4',['../syntax-tensors.html#logspaceswr4',1,'']]],
  ['logspacetensor_59',['LogspaceTensor',['../syntax-tensors.html#logspacetensor',1,'']]],
  ['logspacevec_60',['LogspaceVec',['../syntax-tensors.html#logspacevec',1,'']]],
  ['logspacewffr4_61',['LogspaceWFFR4',['../syntax-tensors.html#logspacewffr4',1,'']]],
  ['logspacewr2_62',['LogspaceWR2',['../syntax-tensors.html#logspacewr2',1,'']]],
  ['logspacewsr4_63',['LogspaceWSR4',['../syntax-tensors.html#logspacewsr4',1,'']]],
  ['logspacewwr4_64',['LogspaceWWR4',['../syntax-tensors.html#logspacewwr4',1,'']]],
  ['loop_65',['loop',['../tutorials-models-vectorization.html#autotoc_md155',1,'For loop'],['../python-examples-statistical.html#autotoc_md238',1,'Run the training loop']]],
  ['loop_20versus_20vectorization_3a_20a_20numerical_20experiment_66',['For loop versus vectorization: A numerical experiment',['../tutorials-models-vectorization.html#autotoc_md154',1,'']]]
];
