var searchData=
[
  ['a_20continuous_20polefigure_0',['Plot a continuous polefigure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md184',1,'']]],
  ['a_20device_1',['Specifying a device',['../tutorials-models-evaluation-device.html#autotoc_md119',1,'']]],
  ['a_20different_20device_2',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md120',1,'']]],
  ['a_20discrete_20inverse_20pole_20figure_3',['Plot a discrete inverse pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md182',1,'']]],
  ['a_20discrete_20pole_20figure_4',['Plot a discrete pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md181',1,'']]],
  ['a_20fixed_20condition_5',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md232',1,'']]],
  ['a_20guide_20and_20training_20hyperparameters_6',['Setup a guide and training hyperparameters',['../python-examples-statistical.html#autotoc_md237',1,'']]],
  ['a_20hierarchical_20statistical_20model_7',['Convert the model to a hierarchical statistical model',['../python-examples-statistical.html#autotoc_md235',1,'']]],
  ['a_20linear_20solver_8',['Nonlinear solvers now reference a linear solver',['../migration-200-210.html#linear_solver',1,'']]],
  ['a_20model_9',['Loading a model',['../tutorials-getting-started.html#autotoc_md114',1,'']]],
  ['a_20model_20from_20the_20input_20file_10',['Loading a model from the input file',['../tutorials-models-running-your-first-model.html#autotoc_md148',1,'']]],
  ['a_20numerical_20experiment_11',['For loop versus vectorization: A numerical experiment',['../tutorials-models-vectorization.html#autotoc_md154',1,'']]],
  ['a_20symbolic_20example_12',['A symbolic example',['../system-models.html#a-symbolic-example',1,'']]],
  ['a_20torch_20tensor_13',['Wrapping a torch tensor',['../tutorials-tensors-tensor-creation.html#autotoc_md247',1,'']]],
  ['actual_20model_14',['actual model',['../python-examples-deterministic.html#autotoc_md188',1,'Setup the actual model'],['../python-examples-statistical.html#autotoc_md226',1,'Setup the actual model']]],
  ['actually_20setup_20the_20model_15',['Actually setup the model',['../python-examples-deterministic.html#autotoc_md189',1,'Actually setup the model'],['../python-examples-statistical.html#autotoc_md227',1,'Actually setup the model']]],
  ['advanced_20tutorials_16',['Advanced tutorials',['../tutorials.html#autotoc_md256',1,'']]],
  ['advection–diffusion–reaction_17',['Example: combined advection–diffusion–reaction',['../finite-volume.html#autotoc_md38',1,'']]],
  ['advective_20flux_18',['Advective flux',['../finite-volume.html#autotoc_md36',1,'']]],
  ['advectivestress_19',['AdvectiveStress',['../syntax-models.html#advectivestress',1,'']]],
  ['against_20the_20synthetic_20data_20',['Calibrate the model against the synthetic data',['../python-examples-deterministic.html#autotoc_md197',1,'']]],
  ['analysis_21',['Code formatting and static analysis',['../tutorials-contributing.html#autotoc_md95',1,'']]],
  ['and_20configuration_22',['Build system and configuration',['../migration-200-210.html#autotoc_md25',1,'']]],
  ['and_20design_20philosophy_23',['Features and design philosophy',['../index.html#autotoc_md3',1,'']]],
  ['and_20equivalent_20stress_24',['1. Stress measure and equivalent stress',['../python-examples-explain.html#autotoc_md207',1,'']]],
  ['and_20for_20our_20initial_20guess_20at_20the_20parameters_25',['and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['and_20forward_20operators_26',['Model structure and forward operators',['../tutorials-models-running-your-first-model.html#autotoc_md149',1,'']]],
  ['and_20how_20they_20interact_27',['Key components and how they interact',['../python-examples-explain.html#autotoc_md206',1,'']]],
  ['and_20inferred_20posteriors_28',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md240',1,'']]],
  ['and_20integration_20changes_29',['Installation and integration changes',['../migration-200-210.html#autotoc_md24',1,'']]],
  ['and_20ldisolidmechanicsdriver_20removed_30',['&lt;span class=&quot;tt&quot;&gt;SDTSolidMechanicsDriver&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;LDISolidMechanicsDriver&lt;/span&gt; removed',['../migration-211-212.html#sdt-ldi-removed',1,'']]],
  ['and_20rate_20dependent_20flow_20rules_31',['6. Rate-independent and rate-dependent flow rules',['../python-examples-explain.html#autotoc_md212',1,'']]],
  ['and_20regression_20tests_32',['Verification and regression tests',['../finite-volume.html#autotoc_md39',1,'']]],
  ['and_20sample_20our_20repeated_20case_33',['Go back and sample our repeated case',['../python-examples-statistical.html#autotoc_md239',1,'']]],
  ['and_20setting_20up_34',['and setting up',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md168',1,'Importing required libraries and setting up'],['../python-examples-crystal_plasticity-polefigures.html#autotoc_md178',1,'Importing required libraries and setting up']]],
  ['and_20special_20features_35',['Assumptions, limitations, and special features',['../python-examples-explain.html#autotoc_md217',1,'']]],
  ['and_20static_20analysis_36',['Code formatting and static analysis',['../tutorials-contributing.html#autotoc_md95',1,'']]],
  ['and_20strain_20decomposition_37',['Elasticity and strain decomposition',['../python-examples-explain.html#autotoc_md214',1,'']]],
  ['and_20their_20input_20file_20syntax_38',['and their input file syntax',['../syntax-data.html#autotoc_md67',1,'Available objects and their input file syntax'],['../syntax-drivers.html#autotoc_md68',1,'Available objects and their input file syntax'],['../syntax-equationsystems.html#autotoc_md69',1,'Available objects and their input file syntax'],['../syntax-models.html#autotoc_md70',1,'Available objects and their input file syntax'],['../syntax-schedulers.html#autotoc_md71',1,'Available objects and their input file syntax'],['../syntax-settings.html#autotoc_md72',1,'Available objects and their input file syntax'],['../syntax-solvers.html#autotoc_md73',1,'Available objects and their input file syntax'],['../syntax-tensors.html#autotoc_md74',1,'Available objects and their input file syntax']]],
  ['and_20training_20hyperparameters_39',['Setup a guide and training hyperparameters',['../python-examples-statistical.html#autotoc_md237',1,'']]],
  ['and_20tutorials_40',['Guides and Tutorials',['../tutorials.html',1,'']]],
  ['argument_20declaration_41',['Argument declaration',['../tutorials-extension-argument-declaration.html',1,'']]],
  ['arguments_42',['Command-line arguments',['../tutorials-contributing.html#autotoc_md91',1,'']]],
  ['arrheniusparameter_43',['ArrheniusParameter',['../syntax-models.html#arrheniusparameter',1,'']]],
  ['assembly_44',['Model assembly',['../system-models.html#model-assembly',1,'']]],
  ['associative_20plasticity_45',['5. Flow direction: associative plasticity',['../python-examples-explain.html#autotoc_md211',1,'']]],
  ['associativeisotropicplastichardening_46',['AssociativeIsotropicPlasticHardening',['../syntax-models.html#associativeisotropicplastichardening',1,'']]],
  ['associativej2flowdirection_47',['AssociativeJ2FlowDirection',['../syntax-models.html#associativej2flowdirection',1,'']]],
  ['associativekinematicplastichardening_48',['AssociativeKinematicPlasticHardening',['../syntax-models.html#associativekinematicplastichardening',1,'']]],
  ['associativeplasticflow_49',['AssociativePlasticFlow',['../syntax-models.html#associativeplasticflow',1,'']]],
  ['assumptions_50',['Assumptions',['../python-examples-explain.html#autotoc_md218',1,'']]],
  ['assumptions_20limitations_20and_20special_20features_51',['Assumptions, limitations, and special features',['../python-examples-explain.html#autotoc_md217',1,'']]],
  ['at_20a_20fixed_20condition_52',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md232',1,'']]],
  ['at_20run_20at_20a_20fixed_20condition_53',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md232',1,'']]],
  ['at_20the_20parameters_54',['at the parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['automatic_20chain_20rule_55',['Automatic chain rule',['../system-models.html#automatic-chain-rule',1,'']]],
  ['automatic_20dependency_20registration_56',['Automatic dependency registration',['../system-models.html#automatic-dependency-registration',1,'']]],
  ['automatic_20dependency_20resolution_57',['Automatic dependency resolution',['../system-models.html#automatic-dependency-resolution',1,'']]],
  ['automatic_20differentiation_58',['Automatic differentiation',['../tutorials-optimization-automatic-differentiation.html',1,'Automatic differentiation'],['../system-models.html#automatic-differentiation',1,'Automatic differentiation'],['../tutorials-optimization-automatic-differentiation.html#autotoc_md162',1,'Automatic differentiation']]],
  ['automatic_20input_20output_20identification_59',['Automatic input/output identification',['../system-models.html#automatic-input-output-identification',1,'']]],
  ['available_20models_60',['available models',['../tutorials-extension.html#autotoc_md104',1,'Seaching for available models'],['../tutorials-models-running-your-first-model.html#autotoc_md145',1,'Searching for available models']]],
  ['available_20objects_20and_20their_20input_20file_20syntax_61',['Available objects and their input file syntax',['../syntax-data.html#autotoc_md67',1,'Available objects and their input file syntax'],['../syntax-drivers.html#autotoc_md68',1,'Available objects and their input file syntax'],['../syntax-equationsystems.html#autotoc_md69',1,'Available objects and their input file syntax'],['../syntax-models.html#autotoc_md70',1,'Available objects and their input file syntax'],['../syntax-schedulers.html#autotoc_md71',1,'Available objects and their input file syntax'],['../syntax-settings.html#autotoc_md72',1,'Available objects and their input file syntax'],['../syntax-solvers.html#autotoc_md73',1,'Available objects and their input file syntax'],['../syntax-tensors.html#autotoc_md74',1,'Available objects and their input file syntax']]],
  ['avramierofeevnucleation_62',['AvramiErofeevNucleation',['../syntax-models.html#avramierofeevnucleation',1,'']]]
];
