var searchData=
[
  ['temperature_20dependence_0',['Temperature dependence',['../python-examples-explain.html#autotoc_md215',1,'']]],
  ['tendors_1',['Create the input tendors',['../python-examples-statistical.html#autotoc_md228',1,'']]],
  ['tensor_2',['Tensor',['../system-tensors.html',1,'Tensor'],['../syntax-tensors.html#tensor',1,'Tensor']]],
  ['tensor_3',['tensor',['../system-tensors.html#dynamically-shaped-tensor',1,'Dynamically shaped tensor'],['../tutorials-tensors-tensor-creation.html#autotoc_md247',1,'Wrapping a torch tensor']]],
  ['tensor_20broadcasting_4',['Tensor broadcasting',['../system-tensors.html#tensor-broadcasting',1,'']]],
  ['tensor_20creation_5',['Tensor creation',['../tutorials-tensors-tensor-creation.html',1,'Tensor creation'],['../system-tensors.html#tensor-creation',1,'Tensor creation']]],
  ['tensor_20indexing_6',['Tensor indexing',['../system-tensors.html#tensor-indexing',1,'']]],
  ['tensor_20name_7',['Tensor name',['../tutorials-models-model-parameters-revisited.html#autotoc_md142',1,'']]],
  ['tensor_20types_8',['Tensor types',['../tutorials-tensors-tensor-types.html',1,'Tensor types'],['../system-tensors.html#tensor-types',1,'Tensor types'],['../tutorials-tensors-tensor-types.html#autotoc_md251',1,'Tensor types']]],
  ['tensor_20view_9',['Tensor view',['../tutorials-tensors-tensor-view.html',1,'']]],
  ['tensors_10',['Tensors',['../syntax-tensors.html',1,'[Tensors]'],['../tutorials-tensors.html',1,'Tensors']]],
  ['tensors_11',['tensors',['../python-examples-deterministic.html#autotoc_md190',1,'Create the input tensors'],['../system-tensors.html#statically-shaped-tensor',1,'Statically shaped tensors'],['../system-tensors.html#working-with-tensors',1,'Working with tensors']]],
  ['test_12',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md236',1,'']]],
  ['tests_13',['tests',['../tutorials-contributing.html#testing-catch-tests',1,'Catch tests'],['../tutorials-contributing.html#testing-regression-tests',1,'Regression tests'],['../tutorials-contributing.html#testing-unit-tests',1,'Unit tests'],['../finite-volume.html#autotoc_md39',1,'Verification and regression tests'],['../tutorials-contributing.html#testing-verification-tests',1,'Verification tests']]],
  ['the_20actual_20model_14',['the actual model',['../python-examples-deterministic.html#autotoc_md188',1,'Setup the actual model'],['../python-examples-statistical.html#autotoc_md226',1,'Setup the actual model']]],
  ['the_20calibrated_20model_20coefficients_15',['Print the calibrated model coefficients',['../python-examples-deterministic.html#autotoc_md199',1,'']]],
  ['the_20calibrated_20model_20predictions_16',['Plot the calibrated model predictions',['../python-examples-deterministic.html#autotoc_md198',1,'']]],
  ['the_20easy_20way_17',['Evaluating the models: The easy way',['../tutorials-models-model-composition.html#autotoc_md134',1,'']]],
  ['the_20elastic_20strains_18',['Plot some comparisons of the elastic strains',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md177',1,'']]],
  ['the_20forward_20operator_19',['The forward operator',['../tutorials-extension-the-forward-operator.html',1,'']]],
  ['the_20frontend_20',['Choosing the frontend',['../tutorials-models-running-your-first-model.html#autotoc_md147',1,'']]],
  ['the_20hard_20way_21',['Evaluating the models: The hard way',['../tutorials-models-model-composition.html#autotoc_md133',1,'']]],
  ['the_20implicit_20function_20theorem_22',['Remarks on the implicit function theorem',['../tutorials-models-implicit-model.html#autotoc_md124',1,'']]],
  ['the_20initial_20parameter_20values_23',['Run the model with the initial parameter values',['../python-examples-deterministic.html#autotoc_md196',1,'']]],
  ['the_20input_20file_24',['the input file',['../tutorials-models-running-your-first-model.html#autotoc_md148',1,'Loading a model from the input file'],['../tutorials-models-model-composition.html#autotoc_md132',1,'Writing the input file'],['../tutorials-models-running-your-first-model.html#autotoc_md146',1,'Writing the input file']]],
  ['the_20input_20tendors_25',['Create the input tendors',['../python-examples-statistical.html#autotoc_md228',1,'']]],
  ['the_20input_20tensors_26',['Create the input tensors',['../python-examples-deterministic.html#autotoc_md190',1,'']]],
  ['the_20integrated_20model_27',['pyzag driver for the integrated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md172',1,'']]],
  ['the_20llm_20chat_20client_28',['Call the LLM chat client',['../python-examples-explain.html#autotoc_md204',1,'']]],
  ['the_20model_29',['the model',['../python-examples-deterministic.html#autotoc_md189',1,'Actually setup the model'],['../python-examples-statistical.html#autotoc_md227',1,'Actually setup the model'],['../tutorials-models-running-your-first-model.html#autotoc_md150',1,'Evaluating the model'],['../python-examples-deterministic.html#autotoc_md185',1,'Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model'],['../python-examples-statistical.html#autotoc_md222',1,'Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model']]],
  ['the_20model_20against_20the_20synthetic_20data_30',['Calibrate the model against the synthetic data',['../python-examples-deterministic.html#autotoc_md197',1,'']]],
  ['the_20model_20for_20training_31',['the model for training',['../python-examples-deterministic.html#autotoc_md194',1,'Setup the model for training'],['../python-examples-statistical.html#autotoc_md233',1,'Setup the model for training']]],
  ['the_20model_20on_20a_20different_20device_32',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md120',1,'']]],
  ['the_20model_20parameters_33',['the model parameters',['../python-examples-deterministic.html#autotoc_md195',1,'Scale the model parameters'],['../python-examples-statistical.html#autotoc_md234',1,'Scale the model parameters']]],
  ['the_20model_20parameters_20with_20random_20values_34',['the model parameters with random values',['../python-examples-deterministic.html#autotoc_md191',1,'Replace the model parameters with random values'],['../python-examples-statistical.html#autotoc_md229',1,'Replace the model parameters with random values']]],
  ['the_20model_20to_20a_20hierarchical_20statistical_20model_35',['Convert the model to a hierarchical statistical model',['../python-examples-statistical.html#autotoc_md235',1,'']]],
  ['the_20model_20to_20generate_20the_20synthetic_20data_36',['the model to generate the synthetic data',['../python-examples-deterministic.html#autotoc_md192',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md230',1,'Run the model to generate the synthetic data']]],
  ['the_20model_20with_20the_20initial_20parameter_20values_37',['Run the model with the initial parameter values',['../python-examples-deterministic.html#autotoc_md196',1,'']]],
  ['the_20models_3a_20the_20easy_20way_38',['Evaluating the models: The easy way',['../tutorials-models-model-composition.html#autotoc_md134',1,'']]],
  ['the_20models_3a_20the_20hard_20way_39',['Evaluating the models: The hard way',['../tutorials-models-model-composition.html#autotoc_md133',1,'']]],
  ['the_20multiplicative_20model_40',['the multiplicative model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md174',1,'Extract the orientations for the multiplicative model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md173',1,'Simulate for the multiplicative model']]],
  ['the_20multiplicative_20model_20results_41',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md175',1,'']]],
  ['the_20new_20engineering_20material_20model_20library_20version_202_42',['The New Engineering Material model Library, version 2',['../index.html#autotoc_md1',1,'']]],
  ['the_20odf_20for_20the_20multiplicative_20model_20results_43',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md175',1,'']]],
  ['the_20orientations_20for_20the_20multiplicative_20model_44',['Extract the orientations for the multiplicative model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md174',1,'']]],
  ['the_20parameter_20value_45',['the parameter value',['../tutorials-models-model-parameters.html#autotoc_md137',1,'Retrieving the parameter value'],['../tutorials-models-model-parameters.html#autotoc_md138',1,'Updating the parameter value']]],
  ['the_20parameters_46',['the parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['the_20pole_20figures_47',['Plot the pole figures',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md176',1,'']]],
  ['the_20prior_20model_20to_20compare_20to_20the_20repeated_20test_48',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md236',1,'']]],
  ['the_20projectiles_49',['Lauching the projectiles',['../tutorials-extension-model-composition.html#autotoc_md108',1,'']]],
  ['the_20prompt_50',['Build the prompt',['../python-examples-explain.html#autotoc_md203',1,'']]],
  ['the_20repeated_20experiment_51',['Conditions for the repeated experiment',['../python-examples-statistical.html#autotoc_md224',1,'']]],
  ['the_20repeated_20test_52',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md236',1,'']]],
  ['the_20separated_20model_53',['pyzag driver for the separated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md169',1,'']]],
  ['the_20seperated_20model_54',['the seperated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md171',1,'ODF reconstruction for the seperated model'],['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md170',1,'Simulate rolling deformation for the seperated model']]],
  ['the_20stress_20strain_20curve_55',['Simulating the stress-strain curve',['../tutorials-models-transient-driver.html#autotoc_md152',1,'']]],
  ['the_20syntax_20database_56',['Extract the syntax database',['../python-examples-explain.html#autotoc_md202',1,'']]],
  ['the_20synthetic_20data_57',['the synthetic data',['../python-examples-deterministic.html#autotoc_md197',1,'Calibrate the model against the synthetic data'],['../python-examples-deterministic.html#autotoc_md193',1,'Plot the synthetic data'],['../python-examples-statistical.html#autotoc_md231',1,'Plot the synthetic data'],['../python-examples-deterministic.html#autotoc_md192',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md230',1,'Run the model to generate the synthetic data']]],
  ['the_20synthetic_20data_20and_20for_20our_20initial_20guess_20at_20the_20parameters_58',['the synthetic data and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['the_20synthetic_20experimental_20conditions_59',['the synthetic experimental conditions',['../python-examples-deterministic.html#autotoc_md186',1,'Setup the synthetic experimental conditions'],['../python-examples-statistical.html#autotoc_md223',1,'Setup the synthetic experimental conditions']]],
  ['the_20system_20of_20equations_60',['the system of equations',['../tutorials-models-implicit-model.html#autotoc_md122',1,'Defining the system of equations'],['../tutorials-models-implicit-model.html#autotoc_md123',1,'Solving the system of equations']]],
  ['the_20training_20loop_61',['Run the training loop',['../python-examples-statistical.html#autotoc_md238',1,'']]],
  ['the_20variability_20in_20the_20synthetic_20data_20and_20for_20our_20initial_20guess_20at_20the_20parameters_62',['the variability in the synthetic data and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['their_20input_20file_20syntax_63',['their input file syntax',['../syntax-data.html#autotoc_md67',1,'Available objects and their input file syntax'],['../syntax-drivers.html#autotoc_md68',1,'Available objects and their input file syntax'],['../syntax-equationsystems.html#autotoc_md69',1,'Available objects and their input file syntax'],['../syntax-models.html#autotoc_md70',1,'Available objects and their input file syntax'],['../syntax-schedulers.html#autotoc_md71',1,'Available objects and their input file syntax'],['../syntax-settings.html#autotoc_md72',1,'Available objects and their input file syntax'],['../syntax-solvers.html#autotoc_md73',1,'Available objects and their input file syntax'],['../syntax-tensors.html#autotoc_md74',1,'Available objects and their input file syntax']]],
  ['theorem_64',['Remarks on the implicit function theorem',['../tutorials-models-implicit-model.html#autotoc_md124',1,'']]],
  ['thermaldeformationjacobian_65',['ThermalDeformationJacobian',['../syntax-models.html#thermaldeformationjacobian',1,'']]],
  ['thermaleigenstrain_66',['ThermalEigenstrain',['../syntax-models.html#thermaleigenstrain',1,'']]],
  ['thermosetting_20pyrolysis_67',['Thermosetting Pyrolysis',['../thermosetting-pyrolysis.html',1,'']]],
  ['they_20interact_68',['Key components and how they interact',['../python-examples-explain.html#autotoc_md206',1,'']]],
  ['time_20compilation_69',['Just-in-time compilation',['../tutorials-models-just-in-time-compilation.html',1,'']]],
  ['to_20a_20hierarchical_20statistical_20model_70',['Convert the model to a hierarchical statistical model',['../python-examples-statistical.html#autotoc_md235',1,'']]],
  ['to_20compare_20to_20the_20repeated_20test_71',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md236',1,'']]],
  ['to_20equationsystems_20nonlinearsystem_72',['Migration to EquationSystems (&lt;span class=&quot;tt&quot;&gt;NonlinearSystem&lt;/span&gt;)',['../migration-200-210.html#eqsys',1,'']]],
  ['to_20explain_20neml2_20input_20file_20in_20natural_20language_73',['Use LLM to explain NEML2 input file in natural language',['../python-examples-explain.html',1,'']]],
  ['to_20generate_20the_20synthetic_20data_74',['to generate the synthetic data',['../python-examples-deterministic.html#autotoc_md192',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md230',1,'Run the model to generate the synthetic data']]],
  ['to_20how_20we_20calibrate_20the_20model_75',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model',['../python-examples-deterministic.html#autotoc_md185',1,'']]],
  ['to_20how_20we_20train_20the_20model_76',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model',['../python-examples-statistical.html#autotoc_md222',1,'']]],
  ['to_20input_20files_77',['Connection to input files',['../tutorials-extension-connection-to-input-files.html',1,'']]],
  ['to_20the_20repeated_20test_78',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md236',1,'']]],
  ['to_20v2_201_200_79',['Migrating from v2.0.0 to v2.1.0',['../migration-200-210.html',1,'']]],
  ['to_20v2_201_202_80',['Migrating from v2.1.1 to v2.1.2',['../migration-211-212.html',1,'']]],
  ['tools_81',['Dimensional indexing tools',['../tutorials-tensors-indexing.html#autotoc_md246',1,'']]],
  ['top_20level_20sections_82',['New top-level sections',['../migration-200-210.html#autotoc_md20',1,'']]],
  ['torch_20tensor_83',['Wrapping a torch tensor',['../tutorials-tensors-tensor-creation.html#autotoc_md247',1,'']]],
  ['touched_20my_20data_84',['Who touched my data?',['../tutorials-tensors-tensor-view.html#autotoc_md253',1,'']]],
  ['tracing_85',['Tracing',['../tutorials-models-just-in-time-compilation.html#autotoc_md128',1,'']]],
  ['tracing_86',['Event tracing',['../system-schedulers.html#autotoc_md87',1,'']]],
  ['train_20the_20model_87',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we train the model',['../python-examples-statistical.html#autotoc_md222',1,'']]],
  ['training_88',['training',['../python-examples-deterministic.html#autotoc_md194',1,'Setup the model for training'],['../python-examples-statistical.html#autotoc_md233',1,'Setup the model for training']]],
  ['training_20hyperparameters_89',['Setup a guide and training hyperparameters',['../python-examples-statistical.html#autotoc_md237',1,'']]],
  ['training_20loop_90',['Run the training loop',['../python-examples-statistical.html#autotoc_md238',1,'']]],
  ['transient_20driver_91',['Transient driver',['../tutorials-models-transient-driver.html',1,'']]],
  ['transientdriver_92',['TransientDriver',['../syntax-drivers.html#transientdriver',1,'']]],
  ['transientdriver_20into_20implicitupdate_93',['Predictor moved from &lt;span class=&quot;tt&quot;&gt;TransientDriver&lt;/span&gt; into &lt;span class=&quot;tt&quot;&gt;ImplicitUpdate&lt;/span&gt;',['../migration-211-212.html#predictor-migration',1,'']]],
  ['transition_20criterion_94',['7. Kocks–Mecking transition criterion',['../python-examples-explain.html#autotoc_md213',1,'']]],
  ['transport_20model_20building_20blocks_95',['Finite volume transport model building blocks',['../finite-volume.html#autotoc_md37',1,'']]],
  ['true_20posteriors_20and_20inferred_20posteriors_96',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md240',1,'']]],
  ['tutorials_97',['Guides and Tutorials',['../tutorials.html',1,'']]],
  ['tutorials_98',['tutorials',['../tutorials.html#autotoc_md256',1,'Advanced tutorials'],['../tutorials.html#autotoc_md255',1,'Basic tutorials']]],
  ['types_99',['types',['../tutorials-models-input-file.html#autotoc_md125',1,'Custom types'],['../tutorials-tensors-tensor-types.html',1,'Tensor types'],['../system-tensors.html#tensor-types',1,'Tensor types'],['../tutorials-tensors-tensor-types.html#autotoc_md251',1,'Tensor types']]]
];
