var searchData=
[
  ['c_20backend_0',['C backend',['../install.html#autotoc_md12',1,'C++ backend'],['../tutorials-contributing.html#testing-cpp',1,'C++ backend']]],
  ['c_20project_1',['Downstream C++ project',['../tutorials-getting-started.html#autotoc_md112',1,'']]],
  ['calibrate_20the_20model_2',['Setup parameters related to &lt;em&gt;how&lt;/em&gt; we calibrate the model',['../python-examples-deterministic.html#autotoc_md185',1,'']]],
  ['calibrate_20the_20model_20against_20the_20synthetic_20data_3',['Calibrate the model against the synthetic data',['../python-examples-deterministic.html#autotoc_md197',1,'']]],
  ['calibrated_20model_20coefficients_4',['Print the calibrated model coefficients',['../python-examples-deterministic.html#autotoc_md199',1,'']]],
  ['calibrated_20model_20predictions_5',['Plot the calibrated model predictions',['../python-examples-deterministic.html#autotoc_md198',1,'']]],
  ['calibration_6',['Calibration',['../tutorials-optimization-parameter-calibration.html#autotoc_md164',1,'']]],
  ['calibration_7',['calibration',['../python-examples-deterministic.html',1,'Deterministic material model calibration'],['../tutorials-optimization-parameter-calibration.html',1,'Parameter calibration']]],
  ['call_20the_20llm_20chat_20client_8',['Call the LLM chat client',['../python-examples-explain.html#autotoc_md204',1,'']]],
  ['calling_20forward_20operators_9',['Calling forward operators',['../tutorials-getting-started.html#autotoc_md115',1,'']]],
  ['case_10',['Go back and sample our repeated case',['../python-examples-statistical.html#autotoc_md239',1,'']]],
  ['catch_20tests_11',['Catch tests',['../tutorials-contributing.html#testing-catch-tests',1,'']]],
  ['cell_20edge_20interpolation_12',['Cell-edge interpolation',['../finite-volume.html#autotoc_md34',1,'']]],
  ['centermillerindex_13',['CenterMillerIndex',['../syntax-tensors.html#centermillerindex',1,'']]],
  ['centerquaternion_14',['CenterQuaternion',['../syntax-tensors.html#centerquaternion',1,'']]],
  ['centerr2_15',['CenterR2',['../syntax-tensors.html#centerr2',1,'']]],
  ['centerr3_16',['CenterR3',['../syntax-tensors.html#centerr3',1,'']]],
  ['centerr4_17',['CenterR4',['../syntax-tensors.html#centerr4',1,'']]],
  ['centerrot_18',['CenterRot',['../syntax-tensors.html#centerrot',1,'']]],
  ['centerscalar_19',['CenterScalar',['../syntax-tensors.html#centerscalar',1,'']]],
  ['centersffr4_20',['CenterSFFR4',['../syntax-tensors.html#centersffr4',1,'']]],
  ['centersfr3_21',['CenterSFR3',['../syntax-tensors.html#centersfr3',1,'']]],
  ['centersr2_22',['CenterSR2',['../syntax-tensors.html#centersr2',1,'']]],
  ['centerssr4_23',['CenterSSR4',['../syntax-tensors.html#centerssr4',1,'']]],
  ['centerswr4_24',['CenterSWR4',['../syntax-tensors.html#centerswr4',1,'']]],
  ['centertensor_25',['CenterTensor',['../syntax-tensors.html#centertensor',1,'']]],
  ['centervec_26',['CenterVec',['../syntax-tensors.html#centervec',1,'']]],
  ['centerwffr4_27',['CenterWFFR4',['../syntax-tensors.html#centerwffr4',1,'']]],
  ['centerwr2_28',['CenterWR2',['../syntax-tensors.html#centerwr2',1,'']]],
  ['centerwsr4_29',['CenterWSR4',['../syntax-tensors.html#centerwsr4',1,'']]],
  ['centerwwr4_30',['CenterWWR4',['../syntax-tensors.html#centerwwr4',1,'']]],
  ['chabocheplastichardening_31',['ChabochePlasticHardening',['../syntax-models.html#chabocheplastichardening',1,'']]],
  ['chain_20rule_32',['Automatic chain rule',['../system-models.html#automatic-chain-rule',1,'']]],
  ['challenge_201_3a_20obtaining_20parameter_20derivatives_20of_20recursive_20nonlinear_20functions_33',['Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions',['../tutorials-optimization-pyzag.html#autotoc_md165',1,'']]],
  ['challenge_202_3a_20data_20scarcity_34',['Challenge 2: Data scarcity',['../tutorials-optimization-pyzag.html#autotoc_md166',1,'']]],
  ['challenge_203_3a_20uncertainty_20quantification_35',['Challenge 3: Uncertainty quantification',['../tutorials-optimization-pyzag.html#autotoc_md167',1,'']]],
  ['changed_36',['Settings defaults/keys changed',['../migration-200-210.html#autotoc_md22',1,'']]],
  ['changes_37',['changes',['../migration-200-210.html#autotoc_md23',1,'Binary utility changes'],['../migration-200-210.html#autotoc_md19',1,'Input file changes'],['../migration-211-212.html#autotoc_md29',1,'Input file changes'],['../migration-200-210.html#autotoc_md24',1,'Installation and integration changes']]],
  ['chat_20client_38',['Call the LLM chat client',['../python-examples-explain.html#autotoc_md204',1,'']]],
  ['chemical_20reactions_39',['Chemical Reactions',['../chemical-reactions.html',1,'']]],
  ['choosing_20the_20frontend_40',['Choosing the frontend',['../tutorials-models-running-your-first-model.html#autotoc_md147',1,'']]],
  ['citing_20neml2_41',['Citing NEML2',['../index.html#autotoc_md4',1,'']]],
  ['class_42',['Base class',['../system-equationsystems.html#autotoc_md77',1,'']]],
  ['client_43',['Client',['../python-examples-explain.html#autotoc_md201',1,'']]],
  ['client_44',['Call the LLM chat client',['../python-examples-explain.html#autotoc_md204',1,'']]],
  ['cmake_20integration_45',['CMake integration',['../external-project-integration.html#autotoc_md15',1,'']]],
  ['code_20formatting_20and_20static_20analysis_46',['Code formatting and static analysis',['../tutorials-contributing.html#autotoc_md95',1,'']]],
  ['code_20naming_20conventions_47',['Source code naming conventions',['../tutorials-naming-conventions.html#autotoc_md160',1,'']]],
  ['coefficients_48',['Print the calibrated model coefficients',['../python-examples-deterministic.html#autotoc_md199',1,'']]],
  ['combined_20advection–diffusion–reaction_49',['Example: combined advection–diffusion–reaction',['../finite-volume.html#autotoc_md38',1,'']]],
  ['command_20line_20arguments_50',['Command-line arguments',['../tutorials-contributing.html#autotoc_md91',1,'']]],
  ['compare_20priors_20true_20posteriors_20and_20inferred_20posteriors_51',['Compare priors, true posteriors, and inferred posteriors',['../python-examples-statistical.html#autotoc_md240',1,'']]],
  ['compare_20to_20the_20repeated_20test_52',['Sample the prior model to compare to the repeated test',['../python-examples-statistical.html#autotoc_md236',1,'']]],
  ['comparisons_20of_20the_20elastic_20strains_53',['Plot some comparisons of the elastic strains',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md177',1,'']]],
  ['compilation_54',['Just-in-time compilation',['../tutorials-models-just-in-time-compilation.html',1,'']]],
  ['complete_20input_20file_55',['Complete input file',['../reactive-infiltration.html#autotoc_md47',1,'']]],
  ['components_56',['Installation layout/components',['../migration-200-210.html#autotoc_md26',1,'']]],
  ['components_20and_20how_20they_20interact_57',['Key components and how they interact',['../python-examples-explain.html#autotoc_md206',1,'']]],
  ['composedmodel_58',['ComposedModel',['../syntax-models.html#composedmodel',1,'']]],
  ['composition_59',['composition',['../tutorials-extension-model-composition.html',1,'Model composition'],['../tutorials-models-model-composition.html',1,'Model composition'],['../system-models.html#model-composition',1,'Model composition']]],
  ['computing_60',['Heterogeneous computing',['../system-schedulers.html#autotoc_md81',1,'']]],
  ['condition_61',['Now sample at run at a fixed condition',['../python-examples-statistical.html#autotoc_md232',1,'']]],
  ['conditions_62',['conditions',['../python-examples-deterministic.html#autotoc_md186',1,'Setup the synthetic experimental conditions'],['../python-examples-statistical.html#autotoc_md223',1,'Setup the synthetic experimental conditions']]],
  ['conditions_20for_20the_20repeated_20experiment_63',['Conditions for the repeated experiment',['../python-examples-statistical.html#autotoc_md224',1,'']]],
  ['configuration_64',['Build system and configuration',['../migration-200-210.html#autotoc_md25',1,'']]],
  ['configure_20options_65',['Configure options',['../build-customization.html#autotoc_md5',1,'']]],
  ['configure_20presets_66',['Configure presets',['../build-customization.html#autotoc_md6',1,'']]],
  ['connection_20to_20input_20files_67',['Connection to input files',['../tutorials-extension-connection-to-input-files.html',1,'']]],
  ['consistent_20plasticity_68',['Consistent plasticity',['../solid-mechanics.html#autotoc_md51',1,'']]],
  ['constantextrapolationpredictor_69',['ConstantExtrapolationPredictor',['../syntax-models.html#constantextrapolationpredictor',1,'']]],
  ['construct_20the_20odf_20for_20the_20multiplicative_20model_20results_70',['Construct the ODF for the multiplicative model results',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md175',1,'']]],
  ['continuous_20polefigure_71',['Plot a continuous polefigure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md184',1,'']]],
  ['contractinggeometry_72',['ContractingGeometry',['../syntax-models.html#contractinggeometry',1,'']]],
  ['contributing_73',['Contributing',['../tutorials-contributing.html',1,'']]],
  ['control_74',['Mixed stress/strain control',['../solid-mechanics.html#autotoc_md60',1,'']]],
  ['control_20volume_75',['Control volume',['../thermosetting-pyrolysis.html#autotoc_md64',1,'']]],
  ['conventions_76',['Naming Conventions',['../tutorials-naming-conventions.html',1,'']]],
  ['conventions_77',['conventions',['../tutorials-naming-conventions.html#autotoc_md158',1,'Naming conventions'],['../tutorials-naming-conventions.html#autotoc_md160',1,'Source code naming conventions'],['../tutorials-naming-conventions.html#autotoc_md159',1,'Variable naming conventions']]],
  ['convert_20the_20model_20to_20a_20hierarchical_20statistical_20model_78',['Convert the model to a hierarchical statistical model',['../python-examples-statistical.html#autotoc_md235',1,'']]],
  ['copy_79',['View versus copy',['../tutorials-tensors-tensor-view.html#autotoc_md252',1,'']]],
  ['copymillerindex_80',['CopyMillerIndex',['../syntax-models.html#copymillerindex',1,'']]],
  ['copyquaternion_81',['CopyQuaternion',['../syntax-models.html#copyquaternion',1,'']]],
  ['copyr2_82',['CopyR2',['../syntax-models.html#copyr2',1,'']]],
  ['copyr3_83',['CopyR3',['../syntax-models.html#copyr3',1,'']]],
  ['copyr4_84',['CopyR4',['../syntax-models.html#copyr4',1,'']]],
  ['copyrot_85',['CopyRot',['../syntax-models.html#copyrot',1,'']]],
  ['copyscalar_86',['CopyScalar',['../syntax-models.html#copyscalar',1,'']]],
  ['copysffr4_87',['CopySFFR4',['../syntax-models.html#copysffr4',1,'']]],
  ['copysfr3_88',['CopySFR3',['../syntax-models.html#copysfr3',1,'']]],
  ['copysr2_89',['CopySR2',['../syntax-models.html#copysr2',1,'']]],
  ['copyssr4_90',['CopySSR4',['../syntax-models.html#copyssr4',1,'']]],
  ['copyswr4_91',['CopySWR4',['../syntax-models.html#copyswr4',1,'']]],
  ['copyvec_92',['CopyVec',['../syntax-models.html#copyvec',1,'']]],
  ['copywffr4_93',['CopyWFFR4',['../syntax-models.html#copywffr4',1,'']]],
  ['copywr2_94',['CopyWR2',['../syntax-models.html#copywr2',1,'']]],
  ['copywsr4_95',['CopyWSR4',['../syntax-models.html#copywsr4',1,'']]],
  ['copywwr4_96',['CopyWWR4',['../syntax-models.html#copywwr4',1,'']]],
  ['crack_20geometric_20functions_97',['Crack geometric functions',['../phase-field-fracture.html#autotoc_md40',1,'']]],
  ['crackgeometricfunctionat1_98',['CrackGeometricFunctionAT1',['../syntax-models.html#crackgeometricfunctionat1',1,'']]],
  ['crackgeometricfunctionat2_99',['CrackGeometricFunctionAT2',['../syntax-models.html#crackgeometricfunctionat2',1,'']]],
  ['create_20the_20input_20tendors_100',['Create the input tendors',['../python-examples-statistical.html#autotoc_md228',1,'']]],
  ['create_20the_20input_20tensors_101',['Create the input tensors',['../python-examples-deterministic.html#autotoc_md190',1,'']]],
  ['creation_102',['creation',['../tutorials-tensors-tensor-creation.html',1,'Tensor creation'],['../system-tensors.html#tensor-creation',1,'Tensor creation']]],
  ['criterion_103',['7. Kocks–Mecking transition criterion',['../python-examples-explain.html#autotoc_md213',1,'']]],
  ['crystal_20plasticity_104',['Crystal plasticity',['../solid-mechanics.html#autotoc_md61',1,'']]],
  ['crystal_20plasticity_20formulations_105',['Crystal plasticity formulations',['../python-examples-crystal_plasticity-compare_formulations.html',1,'']]],
  ['crystalgeometry_106',['CrystalGeometry',['../syntax-data.html#crystalgeometry',1,'']]],
  ['crystalplasticitystrainpredictor_107',['CrystalPlasticityStrainPredictor',['../syntax-models.html#crystalplasticitystrainpredictor',1,'']]],
  ['csvscalar_108',['CSVScalar',['../syntax-tensors.html#csvscalar',1,'']]],
  ['csvsr2_109',['CSVSR2',['../syntax-tensors.html#csvsr2',1,'']]],
  ['csvvec_110',['CSVVec',['../syntax-tensors.html#csvvec',1,'']]],
  ['cubiccrystal_111',['CubicCrystal',['../syntax-data.html#cubiccrystal',1,'']]],
  ['cubicelasticitytensor_112',['CubicElasticityTensor',['../syntax-models.html#cubicelasticitytensor',1,'']]],
  ['curve_113',['Simulating the stress-strain curve',['../tutorials-models-transient-driver.html#autotoc_md152',1,'']]],
  ['custom_20types_114',['Custom types',['../tutorials-models-input-file.html#autotoc_md125',1,'']]],
  ['customization_115',['Build Customization',['../build-customization.html',1,'']]],
  ['cylindricalchannelgeometry_116',['CylindricalChannelGeometry',['../syntax-models.html#cylindricalchannelgeometry',1,'']]]
];
