var searchData=
[
  ['data_0',['Data',['../syntax-data.html',1,'[Data]'],['../system-data.html',1,'Data'],['../system-data.html#autotoc_md76',1,'Data']]],
  ['data_1',['data',['../python-examples-deterministic.html#autotoc_md197',1,'Calibrate the model against the synthetic data'],['../python-examples-deterministic.html#autotoc_md193',1,'Plot the synthetic data'],['../python-examples-statistical.html#autotoc_md231',1,'Plot the synthetic data'],['../python-examples-deterministic.html#autotoc_md192',1,'Run the model to generate the synthetic data'],['../python-examples-statistical.html#autotoc_md230',1,'Run the model to generate the synthetic data'],['../tutorials-tensors-tensor-view.html#autotoc_md253',1,'Who touched my data?']]],
  ['data_20and_20for_20our_20initial_20guess_20at_20the_20parameters_2',['data and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['data_20scarcity_3',['Challenge 2: Data scarcity',['../tutorials-optimization-pyzag.html#autotoc_md166',1,'']]],
  ['database_4',['Extract the syntax database',['../python-examples-explain.html#autotoc_md202',1,'']]],
  ['declaration_5',['declaration',['../tutorials-extension-argument-declaration.html',1,'Argument declaration'],['../tutorials-extension-argument-declaration.html#autotoc_md97',1,'Parameter declaration'],['../tutorials-extension-argument-declaration.html#autotoc_md96',1,'Variable declaration']]],
  ['decomposition_6',['Elasticity and strain decomposition',['../python-examples-explain.html#autotoc_md214',1,'']]],
  ['defaults_20keys_20changed_7',['Settings defaults/keys changed',['../migration-200-210.html#autotoc_md22',1,'']]],
  ['define_20the_20variability_20in_20the_20synthetic_20data_20and_20for_20our_20initial_20guess_20at_20the_20parameters_8',['Define the variability in the synthetic data and for our initial guess at the parameters',['../python-examples-deterministic.html#autotoc_md187',1,'Define the variability in the synthetic data and for our initial guess at the parameters'],['../python-examples-statistical.html#autotoc_md225',1,'Define the variability in the synthetic data and for our initial guess at the parameters']]],
  ['defining_20the_20system_20of_20equations_9',['Defining the system of equations',['../tutorials-models-implicit-model.html#autotoc_md122',1,'']]],
  ['definition_10',['definition',['../system-models.html#model-definition',1,'Model definition'],['../tutorials-optimization-automatic-differentiation.html#autotoc_md161',1,'Model definition'],['../tutorials-extension-model-composition.html#autotoc_md106',1,'Problem definition'],['../tutorials-optimization-parameter-calibration.html#autotoc_md163',1,'Problem definition']]],
  ['deformation_11',['Simulate rolling deformation',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md180',1,'']]],
  ['deformation_20for_20the_20seperated_20model_12',['Simulate rolling deformation for the seperated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md170',1,'']]],
  ['degradation_20functions_13',['Degradation functions',['../phase-field-fracture.html#autotoc_md41',1,'']]],
  ['denselu_14',['DenseLU',['../syntax-solvers.html#denselu',1,'']]],
  ['density_15',['Strain Energy Density',['../phase-field-fracture.html#autotoc_md42',1,'']]],
  ['dependence_16',['Temperature dependence',['../python-examples-explain.html#autotoc_md215',1,'']]],
  ['dependencies_17',['dependencies',['../dependency-management.html#autotoc_md9',1,'List of dependencies'],['../dependency-management.html#autotoc_md10',1,'Skipping dependencies']]],
  ['dependency_20management_18',['Dependency management',['../dependency-management.html',1,'']]],
  ['dependency_20registration_19',['Automatic dependency registration',['../system-models.html#automatic-dependency-registration',1,'']]],
  ['dependency_20resolution_20',['Automatic dependency resolution',['../system-models.html#automatic-dependency-resolution',1,'']]],
  ['dependency_20search_21',['Dependency search',['../dependency-management.html#autotoc_md8',1,'']]],
  ['dependent_20flow_20rules_22',['6. Rate-independent and rate-dependent flow rules',['../python-examples-explain.html#autotoc_md212',1,'']]],
  ['derivatives_20of_20recursive_20nonlinear_20functions_23',['Challenge 1: Obtaining parameter derivatives of recursive nonlinear functions',['../tutorials-optimization-pyzag.html#autotoc_md165',1,'']]],
  ['description_24',['description',['../tutorials-extension.html#autotoc_md103',1,'Problem description'],['../tutorials-models-implicit-model.html#autotoc_md121',1,'Problem description'],['../tutorials-models-just-in-time-compilation.html#autotoc_md126',1,'Problem description'],['../tutorials-models-model-composition.html#autotoc_md131',1,'Problem description'],['../tutorials-models-model-parameters.html#autotoc_md135',1,'Problem description'],['../tutorials-models-model-parameters-revisited.html#autotoc_md139',1,'Problem description'],['../tutorials-models-running-your-first-model.html#autotoc_md144',1,'Problem description'],['../tutorials-models-transient-driver.html#autotoc_md151',1,'Problem description']]],
  ['design_20philosophy_25',['Features and design philosophy',['../index.html#autotoc_md3',1,'']]],
  ['details_26',['details',['../reactive-infiltration.html#autotoc_md46',1,'Implementation details'],['../thermosetting-pyrolysis.html#autotoc_md65',1,'Implementation details']]],
  ['deterministic_20material_20model_20calibration_27',['Deterministic material model calibration',['../python-examples-deterministic.html',1,'']]],
  ['development_28',['Model development',['../tutorials-contributing.html#autotoc_md90',1,'']]],
  ['device_29',['Device',['../tutorials-models-evaluation-device.html#autotoc_md118',1,'']]],
  ['device_30',['device',['../tutorials-models-evaluation-device.html#autotoc_md120',1,'Evaluating the model on a different device'],['../tutorials-models-evaluation-device.html',1,'Evaluation device'],['../tutorials-models-evaluation-device.html#autotoc_md119',1,'Specifying a device']]],
  ['differencemillerindex_31',['DifferenceMillerIndex',['../syntax-tensors.html#differencemillerindex',1,'']]],
  ['differencequaternion_32',['DifferenceQuaternion',['../syntax-tensors.html#differencequaternion',1,'']]],
  ['differencer2_33',['DifferenceR2',['../syntax-tensors.html#differencer2',1,'']]],
  ['differencer3_34',['DifferenceR3',['../syntax-tensors.html#differencer3',1,'']]],
  ['differencer4_35',['DifferenceR4',['../syntax-tensors.html#differencer4',1,'']]],
  ['differencerot_36',['DifferenceRot',['../syntax-tensors.html#differencerot',1,'']]],
  ['differencescalar_37',['DifferenceScalar',['../syntax-tensors.html#differencescalar',1,'']]],
  ['differencesffr4_38',['DifferenceSFFR4',['../syntax-tensors.html#differencesffr4',1,'']]],
  ['differencesfr3_39',['DifferenceSFR3',['../syntax-tensors.html#differencesfr3',1,'']]],
  ['differencesr2_40',['DifferenceSR2',['../syntax-tensors.html#differencesr2',1,'']]],
  ['differencessr4_41',['DifferenceSSR4',['../syntax-tensors.html#differencessr4',1,'']]],
  ['differenceswr4_42',['DifferenceSWR4',['../syntax-tensors.html#differenceswr4',1,'']]],
  ['differencetensor_43',['DifferenceTensor',['../syntax-tensors.html#differencetensor',1,'']]],
  ['differencevec_44',['DifferenceVec',['../syntax-tensors.html#differencevec',1,'']]],
  ['differencewffr4_45',['DifferenceWFFR4',['../syntax-tensors.html#differencewffr4',1,'']]],
  ['differencewr2_46',['DifferenceWR2',['../syntax-tensors.html#differencewr2',1,'']]],
  ['differencewsr4_47',['DifferenceWSR4',['../syntax-tensors.html#differencewsr4',1,'']]],
  ['differencewwr4_48',['DifferenceWWR4',['../syntax-tensors.html#differencewwr4',1,'']]],
  ['different_20device_49',['Evaluating the model on a different device',['../tutorials-models-evaluation-device.html#autotoc_md120',1,'']]],
  ['differentiation_50',['differentiation',['../tutorials-optimization-automatic-differentiation.html',1,'Automatic differentiation'],['../system-models.html#automatic-differentiation',1,'Automatic differentiation'],['../tutorials-optimization-automatic-differentiation.html#autotoc_md162',1,'Automatic differentiation']]],
  ['diffusionlimitedreaction_51',['DiffusionLimitedReaction',['../syntax-models.html#diffusionlimitedreaction',1,'']]],
  ['dimensional_20indexing_20tools_52',['Dimensional indexing tools',['../tutorials-tensors-indexing.html#autotoc_md246',1,'']]],
  ['direction_3a_20associative_20plasticity_53',['5. Flow direction: associative plasticity',['../python-examples-explain.html#autotoc_md211',1,'']]],
  ['directory_54',['Sub-directory',['../external-project-integration.html#autotoc_md16',1,'']]],
  ['discrete_20inverse_20pole_20figure_55',['Plot a discrete inverse pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md182',1,'']]],
  ['discrete_20pole_20figure_56',['Plot a discrete pole figure',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md181',1,'']]],
  ['discretization_57',['Finite volume discretization',['../finite-volume.html#autotoc_md33',1,'']]],
  ['dislocationobstaclestrengthmap_58',['DislocationObstacleStrengthMap',['../syntax-models.html#dislocationobstaclestrengthmap',1,'']]],
  ['dispatchers_59',['Work dispatchers',['../system-schedulers.html#autotoc_md82',1,'']]],
  ['documentation_60',['Documentation',['../tutorials-contributing.html#autotoc_md94',1,'']]],
  ['downstream_20c_20project_61',['Downstream C++ project',['../tutorials-getting-started.html#autotoc_md112',1,'']]],
  ['driver_62',['Driver',['../system-drivers.html',1,'']]],
  ['driver_63',['driver',['../python-examples-crystal_plasticity-polefigures.html#autotoc_md179',1,'pyzag driver'],['../tutorials-models-transient-driver.html',1,'Transient driver']]],
  ['driver_20for_20the_20integrated_20model_64',['pyzag driver for the integrated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md172',1,'']]],
  ['driver_20for_20the_20separated_20model_65',['pyzag driver for the separated model',['../python-examples-crystal_plasticity-compare_formulations.html#autotoc_md169',1,'']]],
  ['drivers_66',['[Drivers]',['../syntax-drivers.html',1,'']]],
  ['drivers_67',['Optional scheduler hookup in drivers',['../migration-200-210.html#autotoc_md21',1,'']]],
  ['dynamically_20shaped_20tensor_68',['Dynamically shaped tensor',['../system-tensors.html#dynamically-shaped-tensor',1,'']]]
];
