# Verification of ZenerElement (Standard Linear Solid) against the closed-form solution
# under a linear strain ramp followed by a hold.
#
# Reference data is generated by reference.py and stored in reference.csv. The script computes
# the analytical strain history (the imposed loading) and the analytical stress history from the
# Zener ODE for that loading, both in NEML2's Mandel SR2 component order. The .i file loads the
# strain history as the prescribed force, runs the model, and verifies that the produced stress
# matches the analytical reference at every time step.

[Tensors]
  [times]
    type = CSVScalar
    csv_file = 'reference.csv'
    column_names = 'time'
  []
  [strains]
    type = CSVSR2
    csv_file = 'reference.csv'
    column_names = 'exx eyy ezz eyz exz exy'
  []
  [stresses_ref]
    type = CSVSR2
    csv_file = 'reference.csv'
    column_names = 'sxx syy szz syz sxz sxy'
  []
[]

[Drivers]
  [driver]
    type = TransientDriver
    model = 'model'
    prescribed_time = 'times'
    force_SR2_names = 'strain'
    force_SR2_values = 'strains'
    save_as = 'result.pt'
  []
  [verification]
    type = VTestVerification
    driver = 'driver'
    SR2_names = 'output.stress'
    SR2_values = 'stresses_ref'
    # First-order backward-Euler integration of the stiff Maxwell branch limits how tight
    # rtol can go (~2% local truncation at dt/tau = 0.05 in the ramp). 3% absorbs that while
    # still catching sign / factor / missing-term bugs.
    rtol = 3e-2
    atol = 1e-5
  []
[]

[Models]
  [zener]
    type = ZenerElement
    equilibrium_modulus = 1000
    maxwell_modulus = 5000
    maxwell_viscosity = 100
  []
  [integrate_Ev]
    type = SR2BackwardEulerTimeIntegration
    variable = 'viscous_strain'
  []
  [implicit_rate]
    type = ComposedModel
    models = 'zener integrate_Ev'
  []
[]

[EquationSystems]
  [eq_sys]
    type = NonlinearSystem
    model = 'implicit_rate'
    unknowns = 'viscous_strain'
    residuals = 'viscous_strain_residual'
  []
[]

[Solvers]
  [newton]
    type = Newton
    linear_solver = 'lu'
  []
  [lu]
    type = DenseLU
  []
[]

[Models]
  [predictor]
    type = ConstantExtrapolationPredictor
    unknowns_SR2 = 'viscous_strain'
  []
  [update]
    type = ImplicitUpdate
    equation_system = 'eq_sys'
    solver = 'newton'
    predictor = 'predictor'
  []
  [model]
    type = ComposedModel
    models = 'update zener'
    additional_outputs = 'viscous_strain'
  []
[]
