name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published

# Newer commits should cancel old runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          # dependencies: python.version_min
          python-version: "3.9"
      - name: Run black style check
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: black --all-files

  test:
    needs: black
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, gpu_runner]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: applied-material-modeling/neml2-ci@main
        with:
          # dependencies: python.version_min
          python-version: 3.9
          # dependencies: cmake.version_min
          cmake-version: 3.26.1
          # dependencies: torch.version
          torch-version: 2.8.0
          cpu-torch: ${{ matrix.runner != 'gpu_runner' }}
      - name: Install
        run: pip install ".[dev]" -v
      - name: Run tests
        run: pytest -v --junitxml=pytest.xml python/tests
      - name: Test results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: pytest.xml
          check_name: Test Results
          check_run: false
          action_fail: true
          comment_mode: off

  # TODO: Re-enable the wheels job when we get the enterprise runners with larger disk space

  # wheels:
  #   needs: black
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest, macos-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install cibuildwheel
  #       run: pip install cibuildwheel
  #     - name: Build wheels
  #       run: cibuildwheel --output-dir wheelhouse
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         path: wheelhouse/*.whl
  #         name: packages-${{matrix.os}}

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build SDist
        run: pipx run build --sdist
      - name: Upload SDist
        uses: actions/upload-artifact@v4
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          name: package-sdist
          path: dist/*.tar.gz

  PyPI:
    needs: sdist
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: package-sdist
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
